### ISSUE TITLE
Build cpprest failure in my ubuntu.

### ISSUE THREAD

**Issue by JamieLuo** [sony/nmos-cpp#100]
[ 20%] Linking CXX shared library ../Binaries/libcpprest.so
/usr/bin/ld: cannot find /usr/lib: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/cpprest.dir/build.make:500: Binaries/libcpprest.so.2.10] Error 1
make[1]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/cpprest.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

I followed the guide of the building steps in the Docements but when I build the cpprestsdk it will raise the above error messages. I use the recommand version in the guides. Do you know why does it happen. Thank you!

**Comment by garethsb-sony** [comment]
Can you provide the full `/usr/bin/ld` command line from the log? It looks like `ld` is trying to treat the `/usr/lib` directory as a library, which might mean some link flags/env variables are being set incorrectly.

**Comment by JamieLuo** [comment]
Thank you for your respond, now I compiled all the stuff successful in ubuntu 16.04. I don't know why it will fail in ubuntu 19.04. Anyway it's working now. : )
