### ISSUE TITLE
Additional / (slash) character in HTTP requests

### ISSUE THREAD

**Issue by andrewjohnwatts** [sony/nmos-cpp#104]
I've noticed whilst attempting to connect a sender to a receiver (Immediate Activation) that there are additional "/" characters in the HTTP Requests. To be clear, I'm not referring to trailing slashes (as previously raised in other tickets) but duplicate "/" in the middle of a URL.

When pressing "Activate", a GET request is sent to the sender and a little later the receiver - however a pcap reveals that there is an additional "/" after the API version number - resulting in HTTP 404 error message. For example:
`GET /x-nmos/connection/v1.0//single/receivers/70b3d504-2d09-1000-8000-000000000099`

![image](https://user-images.githubusercontent.com/48548514/71896224-1140f780-314b-11ea-9ea1-8d012e942ece.png)

Manually performing this request (without the extra slash) is successful:
`GET /x-nmos/connection/v1.0/single/receivers/70b3d504-2d09-1000-8000-000000000099`

Apologies if I'm missing something obvious here, but so far as I can tell this is a bug?

**Comment by garethsb-sony** [comment]
Thanks for the report. This is a client-side bug. Are you using the *nmos-js* client webapp? (This repo is for the nmos-cpp Registry and Node implementations.)

**Comment by andrewjohnwatts** [comment]
Sorry you're completely right - I'll duplicate this on nmos-js repo.

**Comment by garethsb-sony** [comment]
No worries! Thanks for doing that. Right... over to the other repo. :-)
