### ISSUE TITLE
IS-08 audio channel mapping implementation

### ISSUE THREAD

**Issue by garethsb-sony** [sony/nmos-cpp#111]
Several nmos-cpp users would like IS-08 support. I think we can largely follow the approach of how IS-05 Connection API resources are represented and associated with the IS-04 Node API resources. I.e. I imagine adding `nmos::node_model::channelmapping_resources`

**Comment by kokkookoo** [comment]
Hi , is there any timeline of when to expect the support?

**Comment by garethsb-sony** [comment]
No guarantee, but intention is to work on this during Q2.

**Comment by garethsb-sony** [comment]
Done! (See 253cc74fc34abca4b3cec488da24ae70023a7297 for most of the work.)

**Comment by garethsb-sony** [comment]
After some recent refactoring (primarily in 699654a701a3dae4fa877b57b967bc316f3e611e), here's a picture that explains the current **nmos-cpp-node** IS-08 example scenario.

![IS-08](https://user-images.githubusercontent.com/31761158/101488304-553e0d00-3957-11eb-9266-e3d62189ffd6.png)
