### ISSUE TITLE
Making an audio receiver with a single provided bit-depth results in extra value

### ISSUE THREAD

**Issue by grimmn** [sony/nmos-cpp#112]
Calling the form of `make_audio_receiver` from node_resources.cpp which takes a single `bit_depth` argument constructs a vector of bit depths in order to call the other form. I believe that the intention was for the `{ 1, bit_depth }` argument to construct a vector containing one value equal to `bit_depth` but the initializer list constructor takes precedence resulting in the receiver being created supporting the provided bit depth as well as a bit depth of 1.

**Comment by garethsb-sony** [comment]
Resolved by #113
