### ISSUE TITLE
PTP domain is non-optional in ts-refclk for ST2110

### ISSUE THREAD

**Issue by grimmn** [sony/nmos-cpp#114]
I believe that ST2110-10 specifies that it is not optional to include the PTP domain in the `ts-refclk` attribute of a PTP clock that's not using the `traceable` form.

SMPTE ST 2110-10:2017 Section 8.2
> Devices which are referenced to IEEE1588-2008 shall use the ts-refclk:ptp form, signaling either the grandmaster clockIdentity and domain, or signaling that the PTP is traceable (if it is).

So far as I can tell there is no supported method of easily specifying the domain for SDP generation.

**Comment by garethsb-sony** [comment]
Interesting. This should be raised in AMWA-TV/sdpoker used by the NMOS Testing Tool (AMWA-TV/nmos-testing) since at the moment, the relevant test follows the RFC in allowing the domain number to be omitted: https://github.com/AMWA-TV/sdpoker/blob/master/checkST2110.js#L173-L179

FWIW, nmos-cpp does allow the PTP domain to be set fairly easily if known, since `nmos::sdp_parameters::ts_refclk` includes `ptp_server` which may optionally contain the domain: https://github.com/sony/nmos-cpp/blob/master/Development/nmos/sdp_utils.h#L187-L191

**Comment by garethsb-sony** [comment]
My intention would be to wire up the setting `"ptp_domain_number"` to this. That would be populated for Nodes either via vendor-specific code or as a result of IS-09 System API discovery (we have an internal prototype for this, for JT-NM TR-1001-1 support).

**Comment by garethsb-sony** [comment]
Testing tool issue (https://github.com/Streampunk/sdpoker/issues/25) and PR (https://github.com/AMWA-TV/sdpoker/pull/5).

**Comment by grimmn** [comment]
Yes, the domain number can be added to the `ptp_server` field in `nmos::sdp_parameters::ts_refclk`, I was more thinking that it it wasn't "easy" because the current `make_video/audio/data_sdp_parameters` helpers in `sdp_utils.h/cpp` don't allow the domain to be specified. They all use `make_ts_refclk` which pulls the clock information from the relevant source's `clock_name` field to look up the properties of that clock. For PTP clocks `ptp_server` is populated with the `gmid` field of the node-level clock which can only contain the GMID itself and not the domain according to https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/APIs/schemas/clock_ptp.json.

I can edit the parameters generated by the helpers easily enough, it would just be nice to not have to. This is obviously only an ST2110 specific requirement but those helpers already appear to be setting other ST2110 specific parameters.

**Comment by garethsb-sony** [comment]
Yes, it's been discussed that it was probably an oversight that the IS-04 PTP clock type doesn't include a domain number attribute as well as the Grand Master ID, but for now it has to come from elsewhere. It would seem reasonable to add an additional parameter to `nmos::make_sdp_parameters` to wire through to `nmos::details::make_ts_refclk`. When we push the IS-09 node behaviour implementation, we can hook those things together in the nmos-cpp-node example.

**Comment by grimmn** [comment]
Ok, I'll look at adding the extra parameter for the domain and see what you think of the changes.

**Comment by garethsb-sony** [comment]
FWIW, given nmos/sdp_utils.h is already loosely geared towards ST 2110, I'd be happy to focus on IEEE 1588-2008 and take domain as a number rather than string if that makes sense to you also?

**Comment by grimmn** [comment]
Yeah, that makes sense to me too.

Do you have any preference on the new argument being required or having a default value (most likely 127 from ST2059-2)? The former breaks backwards compatibility while the latter could result in an unexpected/incorrect domain being advertised.

**Comment by garethsb-sony** [comment]
Yes, it's a little tricky in terms of the output too - which is least worst, to create an SDP file that is valid per RFC 7273 but not per ST 2110-10, or to advertise the wrong domain?

I'm coming down on the side of omitting the domain in these circumstances, no matter what ST 2110-10 says.

That would imply that we need a way of indicating omitted domain (the current behaviour)... I feel a magic number coming on (minus one?), at least internally within nmos/sdp_utils.cpp. This needn't be exposed in the interface of nmos/sdp_utils.h, we could just have two versions of the function with and without the domain? Just thinking aloud...

**Comment by grimmn** [comment]
Yeah, my thoughts basically mirror your own, I'll try a few things and see what feels best. Thanks.
