### ISSUE TITLE
Type cast looks wrong in sdp_utils.cpp:1025 wrt the ptime attribute

### ISSUE THREAD

**Issue by duncan-webb** [sony/nmos-cpp#120]
The RFC doesn't explicitly specify a type for the ptime attribute value, rather that it's specified in milliseconds. When the value has microsecond precision the value::as_integer() conversion loses this. The underlying value is stored as a double - would it be valid to change the code to use value::as_double() to retain the precision?

**Comment by garethsb-sony** [comment]
That does look wrong, especially as we're already storing it in `nmos::sdp_parameters` as a double and writing it into SDP files as such.

ST 2110-30 refers to AES67 which elaborates on the (as always) terse RFC 4566 description in Section 8.1 Packet time:

> `a=ptime:<milliseconds>[.<milliseconds decimal>]`
>
> Signaled packet time multiplied by sampling frequency rounded to the nearest integer indicates the number of samples in each packet. The packet time descriptions shall be given with error less than half a sample period so that the calculated number of samples per packet rounds to the intended integer value. In many cases, this requires the inclusion of the `<milliseconds decimal>` in the description.

Thanks for the report! Proposed fix is on its way into master (ought to add a unit test but haven't).

**Comment by garethsb-sony** [comment]
FWIW, the following is found further on in AES67 Section 8.1...

> NOTE The non-integral-millisecond descriptions may not be correctly understood by connection management partners not in compliance with this standard. The description may need to be confined to integer `<millisecond>` values when attempting connection to such partners.

That said, I'm saying this is resolved by 91e2ce2cc59619812ec80a2bc0be30352e193e8d. Thanks, again.

**Comment by duncan-webb** [comment]
Fantastic, thanks Gareth!
