### ISSUE TITLE
make failed - /usr/bin/ld: cannot find -lmint

### ISSUE THREAD

**Issue by CRYPTO-7CA** [sony/nmos-cpp#122]
I encountered a dependency issue today. Here it is
![image](https://user-images.githubusercontent.com/61016421/75045274-0a402f80-54d4-11ea-88c8-66235d569fc2.png)
What is this **mint** library?
Any suggestions?

**Comment by garethsb-sony** [comment]
Sorry, I don't recognise **mint**. Can you examine the makefiles and logs to see why it is linked?

**Comment by CRYPTO-7CA** [comment]
Silly me. I didn't realize I was working on a forked off modified project, that was based on the sony-nmos-cpp repository. I apologize for the distraction.

After executing `git remote show origin` I see, that the URL is not equal to `https://github.com/sony/nmos-cpp.git`
