### ISSUE TITLE
IS-05 immediate activation of many resources

### ISSUE THREAD

**Issue by wsneijers** [sony/nmos-cpp#126]
Hello,

I don't think my issue qualifies as a bug, It's more of a discussion / observation about the way nmos-cpp handles immediate activation(s). As far as I can tell (please correct me if I'm wrong) There seem to be two stages in nmos-cpp for all activation types (immediate, relative, absolute):

1. Handling of the user request. 
When the user makes a PATCH request it is handled by cpprest. As far as I can see all it does in that context is some validation of the request, setup the staged API with the correct information and return the correct status code in a response. It also pushes the activation onto a resource update list and if the activation is immediate it notifies everyone about it. 

2. Handling the activation
Another thread that is responsible for handling all activation's wakes up and handles any applicable items in the resource update list. As far as I can see it is responsible for activating resources at the correct time. 

I could not find a clear definition for immediate activation's in the standard, but I did have a question about this earlier on the [nmos-testing](https://github.com/AMWA-TV/nmos-testing/issues/484) repo. There it became clear to me that for immediate activation's you need to guarantee that the activation is handled by the time the response is returned to the user (step 1). However the response is returned before the resource is activated (step 2). 

You can probably get away with this if you only have a few resources and not al lot of overhead. However for me it goes wrong when trying to activate many resources (64 senders and 64 receivers) with immediate activation in short succession (like the nmos-testing tool does in IS-05-01 test 25).

So my question / point of discussion is simple. Is this the correct way of handling immediate activation's?

To add a foot note to this already long story (sorry about that). I know that it is far more practical for this use-case to use the bulk API. However I think it should also be possible to the single API. But again please correct me if I'm wrong.

**Comment by garethsb-sony** [comment]
Thanks for the well laid out question! Your understanding of the design of the nmos-cpp Connection API and activation implementation is absolutely spot on. The only thing you've missed is that (only) in the case of immediate activation requests the Connection API handler wakes up the activation thread **and then blocks until it has done the activation**. But if you're seeing something different then presumably there's a bug somewhere.

**Comment by wsneijers** [comment]
Really, But how does that work then? Because I don't see how it can wait. As far as I can see, from the staged route registration it calls `handle_connection_resource_patch`. Which in turn calls `handle_immediate_activation_pending` because it is an immediate activation. However that function doesn't wait or block. The `set_reply` is called immediately afterwards. Again correct me if I'm wrong :).

**Comment by garethsb-sony** [comment]
In fact, `handle_immediate_activation_pending` calls `wait_activation_modified` which waits for the activation object to be modified by the connection activation thread.

**Comment by wsneijers** [comment]
Indeed it does block like you explained. It was mainly me not understanding how it worked. Thanks for the clarification!

**Comment by garethsb-sony** [comment]
>  It was mainly me not understanding how it worked.

If you have some hints for some useful documentation or code comments, let me know (actually, your initial description in this issue is probably a good start!!)
