### ISSUE TITLE
Add connection_data base_address and port

### ISSUE THREAD

**Issue by aholzinger** [sony/nmos-cpp#130]
With this patch
https://github.com/aholzinger/nmos-cpp/commit/98e773d077962e304d2d86054cd4b9aa38c21130
a user/client can extract also connection_data::base_address and port with sdp_parameters.

**Comment by garethsb-sony** [comment]
I believe this is unnecessary since the information is already extracted by `get_session_description_transport_params` and thus also by the convenience function `parse_session_description`.
