### ISSUE TITLE
Report transport file also for non running senders

### ISSUE THREAD

**Issue by aholzinger** [sony/nmos-cpp#131]
Why not reporting SDP transportfile also for senders that are completely configure, but just not running?

With this patch
https://github.com/aholzinger/nmos-cpp/commit/47180a04fa707b62714219286acb936b9ccd6a67
this is possible.

**Comment by garethsb-sony** [comment]
Will wait for resolution of https://github.com/AMWA-TV/nmos-device-connection-management/issues/110

**Comment by aholzinger** [comment]
What about the idea making this configurable by a runtime parameter (in the json config)?

**Comment by garethsb-sony** [comment]
At the moment, I expect that we can clear up the spec quite quickly, and will follow that.

**Comment by garethsb-sony** [comment]
Resolved by 34f6d2034a9e1c7f31b433ebdbb183059b3ab33b based on https://github.com/AMWA-TV/nmos-device-connection-management/pull/111
