### ISSUE TITLE
questions on dns-sd and the host_addresses list

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#149]
I am running the nmos-cpp-registry on a couple of raspberry pi-based systems and getting different behavior.  This is probably due to my ignorance with respect to system configuration but I will ask my potentially stupid questions anyway.

My simple test  for some level of working is to start the registry on the raspberry pi, run the Riedel NMOS explorer on a windows PC and see if the registry appears as a node in the explorer. On one system, this passes, on another, it does not.

On the system under test that works, there are 2 network interfaces. One is for a static address on a subnet which does not have a dhcp server or a dns server. The other network interface is the wifi and this is connected to a subnet with dhcp and dns services. The windows PC is connected to both subnets. 

The other system under test just has the static address an a subnet without dhscp or a dns server. For the most part, the NMOS explorer does not see the nmos-cpp-registry. Sometimes, it seems to find it via P2P but mostly not.

On the first system under test, if the wifi is turned off, then it seems to behave like the second system.

So I assume I need a dns server in the subnet for this to work on both configurations. This is my stupid question.

My second question is that I start the registry with a host_address of the static ip address and an host_addresses list of just the static ip address but on the system with the wifi turned on, it still seems to send information out on the wifi interface even though that interface is not in the list of host_addresses. I was thinking that the host_addresses list was the list of interfaces which could be used for nmos-cpp-registry related traffic but it seems to use all the interfaces on the system even though I thought I was telling it not to. 

Apparently, I don't understand what the purpose of specifying a list of host_addresses. So my second question is if the host_addresses list is a subset of all the interfaces on the system, should the registry be using any interfaces which are not in the indicated subset?

Thanks.

**Comment by jwpwh** [comment]
Looks like the wifi did not matter. It was tried again and the explorer took some time (17 seconds) but it eventually found the registry. 

On another PC though, it could not find the registry. Wireshark seemed to show that the mdns packets were not getting in. Looking into whether the switch is keeping these out.

Still want to know about what effect host_addresses is supposed to have.

Thanks.

**Comment by garethsb-sony** [comment]
First off, investigating DNS-SD advertising and browsing vagaries on different platforms with the various, variously buggy, implementations, and different network environments, has been by far the biggest time sink on this project. So I feel your pain.

From settings: https://github.com/sony/nmos-cpp/blob/6434665c3414d6c785d3300e8b343ba7e03fade4/Development/nmos/settings.h#L54
Setting `host_addresses` is primarily about what is advertised in the JSON and HTTP response headers.

As it stands mDNS advertisements are not limited to particular interfaces.

**Comment by jwpwh** [comment]
Good enough. I guess there is a reason they call them demons. :)
 
Thanks for your help.

**Comment by garethsb-sony** [comment]
Ha ha ha! 😀
Always very happy to look at docs or code PRs if there's something we can do better!
