### ISSUE TITLE
Manifest Base URL not working

### ISSUE THREAD

**Issue by TobiasThierolf** [sony/nmos-cpp#151]
Hello,

related information about the manifest base url handling can be found here: [Manifest Base](https://amwa-tv.github.io/nmos-parameter-registers/branches/master/device-control-types/manifest-base.html).

I am not 100% sure if the manifest base feature is meant to be supported or if I understood it correctly. 
The mainfest-base controls section exist on the device section in the node api. My expectation now is that the manifest files should be accessible via all of the given four base address in the control section.
```
{
"href": "http://192.168.1.15:4000/x-manifest/",
"type": "urn:x-nmos:control:manifest-base/v1.0"
},
{
"href": "http://192.168.2.15:4000/x-manifest/",
"type": "urn:x-nmos:control:manifest-base/v1.0"
},
{
"href": "http://192.168.30.15:4000/x-manifest/",
"type": "urn:x-nmos:control:manifest-base/v1.0"
},
{
"href": "http://192.168.20.15:4000/x-manifest/",
"type": "urn:x-nmos:control:manifest-base/v1.0"
}
```

The server which runs the nmos-cpp library (an nmos node) has 4 network interfaces and those are appearing in the nmos data model.

Two of the four interfaces are for media data only. The other two interfaces are used for control.
The interface "mlnx1" in the code section below is the interface that is used by sender/3 for media data and is bound to 192.168.1.15.
```
...
{
"description": "sender/3",
"device_id": "0a517ada-44b5-59f0-92f0-ba70b3a184d4",
"flow_id": "f7dcb1fe-cc6a-5c1a-ae1e-ce7d7558cfb8",
"id": "d1709e25-f194-5e09-92ab-6fe3f7c62212",
"interface_bindings": [
"mlnx1"
],
"label": "sender/3",
"manifest_href": "http://192.168.1.15:4000/x-manifest/senders/d1709e25-f194-5e09-92ab-6fe3f7c62212/manifest",
"subscription": {
"active": true,
"receiver_id": null
},
"tags": {},
"transport": "urn:x-nmos:transport:rtp.mcast",
"version": "1591690270:909943488"
}
...
```

If I want to read the manifest file from our control network via 192.168.30.15 the following request is send: http://192.168.30.15:4000/x-manifest/senders/d1709e25-f194-5e09-92ab-6fe3f7c62212/manifest, but then an error code 404 is received as response.
```
{
"code": 404,
"debug": null,
"error": "Not Found"
}
```
Generally  I can use all the network interfaces on our server to access the node api, the control api and so on without any problems. The only thing that is not working is the manifest file.

Best Regards,
Tobias

**Comment by garethsb-sony** [comment]
This does sound surprising. There should be no difference between the way the Node API is served and the way the manifest files are served. If the manifest file is accessible correctly via one of the URLs, it should be accessible on the others, especially if Node API is also accessible on all ports successfully.

What response do you get from the levels above?
* http://192.168.30.15:4000/
*  http://192.168.30.15:4000/x-manifest/
*  http://192.168.30.15:4000/x-manifest/senders/

**Comment by TobiasThierolf** [comment]
The level http://192.168.30.15:4000/ works and I get the normal overview with log, settings and x-nmos. The others reply with the same 404 error code as mentioned above.

**Comment by garethsb-sony** [comment]
> The level http://192.168.30.15:4000/ works and I get the normal overview with log, settings and x-nmos. The others reply with the same 404 error code as mentioned above.

The array response _doesn't_ include `"x-manifest/"`?

**Comment by TobiasThierolf** [comment]
No It doesn't contain an x-manifest. Never saw this node. Maybe I am doing something wrong here.

**Comment by TobiasThierolf** [comment]
The x-manifest is not showing up on my nmos-cpp-node application.

**Comment by garethsb-sony** [comment]
I've just tried it here and all OK. How are you configuring the ports? Are you setting `node_port` and `manifest_port` individually (and to same or different values?) or are you using the shorthand `http_port` to get all APIs on the same port?

**Comment by TobiasThierolf** [comment]
Right now I am using the shorthand http_port.

**Comment by garethsb-sony** [comment]
OK, that's what I've just tried locally, slightly different branch... I see `"x-manifest/"` alongside `"x-nmos/"` etc. on both my interfaces, and the manifest files are GET-able (apart from the IS-07 senders which report 404 with `"Sender is not configured with a transport file"`, as expected).

Can't yet think what the difference could be in your environment...

**Comment by TobiasThierolf** [comment]
Mmh I can't tell what the difference is. I will check with a debugger maybe I can find an explanation for this behavior on my systems. I will keep you informed as soon as I find something.

**Comment by TobiasThierolf** [comment]
Ok, so I've checked all occurrences of the string x-manifest and found more or less three places and  I checked if they are getting called.

/manifest_api.cpp@16 - make_manifest_api - not called
/node_resources.cpp@100 - make_device - creates the control section - called
/node_resources.cpp@477 - make_manifest_api_manifest - called

The line numbers might be slightly off because of some debug prints I'd to put in place. All the code parts that are listed are basically belonging to a changeset from March 23th. My version is a bit outdated by it contains already changesets from May. My initial node implementation is quite old, so it might not contain any calls that are specific to the manifest_api, is there something I need to add or should this be handled internally in the nmos library?

**Comment by garethsb-sony** [comment]
All the moving parts are designed as much as possible so you can choose to wire them up differently, but if you are using `nmos::experimental::make_node_server` to put the APIs together over the `model` and vendor-specific bits, I'd expect the call to `make_manifest_api` here:

https://github.com/sony/nmos-cpp/blob/f5dce9d6ff6e4dc2b575dc634c1b28f39f6d41bd/Development/nmos/node_server.cpp#L49

**Comment by TobiasThierolf** [comment]
Ok, that explains it for me. I had to make the make_node_server function call in a different way for some reasons (node_server is a class member in my implementation) and the issue appears because of this change.

Thank you for your support and sorry for the inconvenience!
