### ISSUE TITLE
Connecting a ST 2022-7 sender to non ST 2022-7 receiver fails.

### ISSUE THREAD

**Issue by TobiasThierolf** [sony/nmos-cpp#162]
Hello everybody,

In the current situation I am able to connect my own (non ST 2022-7) senders to my receivers without any issues. The next step was to put an Embrionix module into the picture which supports ST 2022-7 and I was expecting that I am able to connect the stream from the Embrionix to our devices. Unfortunately this didn't work.

I see that an exception is thrown in the merge_patch function in the json_utils.cpp:
```
if (value.size() != patch.size())
{
   if (!permissive) throw web::json::json_exception(_XPLATSTR("patch error - inconsistent array size"));                    
}
```

This function is being called from the connection_api.cpp handle_connection_resource_patch function. I was able to resolve this issue already by simply setting the permissive parameter to true, but I am not sure if this is the proper solution here.

I am not sure if such a connection is forbidden or something. From my point of view I was expecting that the second leg in the SDP file is simply ignored and the first one is used to make the connection.

**Comment by garethsb-sony** [comment]
The PATCH request `transport_params` must have the same number of 'legs' as the Receiver being configured. It is the client's responsibility to make this right. What controller are you using?

**Comment by TobiasThierolf** [comment]
For this test I used the Riedel NMOS Explorer 1.6.3.

**Comment by garethsb-sony** [comment]
@jasperpeeters

**Comment by TobiasThierolf** [comment]
Thank you for the information. Just to wrap it up, there is no specific action that needs to be taken by the nmos node. The responsibility for this is in the client / controller instance.

**Comment by jasperpeeters** [comment]
@TobiasThierolf 
This was a known bug (see [here](https://github.com/AMWA-TV/nmos-device-connection-management/issues/109)), which has been fixed  early this year - but since then there was no new release.
I triggered a new release of the NMOS Explorer including this fix, which should solve the problem. 
I'll notify you when this is the case, should be very soon.
