### ISSUE TITLE
Question: building as shared libraries instead of static?

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#169]
Is there any support for building and using the nmos-cpp libraries as shared libraries instead of static? 

I was thinking this might allow my application and the nmos-cpp code to use different make systems (qmake vs cmake). Use as shared libraries might have impact on memory allocation and the library api and in a quick scan, I did not see obvious support for shared libraries so I am guessing the answer is no but thought it would be worth asking.

Thanks.

**Comment by garethsb-sony** [comment]
Short answer - no.
Long answer - we've avoided this thus far for two main reasons: (a) evolving spec and understanding of which nmos-cpp components will be used by the majority of users, and (b) evolving platform dependencies (compiler/std, boost and cpprestsdk types which don't maintain ABI compatibility would be needed in the library interfaces however we slice it). We've all gained more experience over the last couple of years about which interfaces of nmos-cpp are most utilized by Node implementers, so it may be a reasonable goal, but the other issue is confounding. Does using a separate build system for the application prohibit consuming the static libraries built with cmake/conan by nmos-cpp?

**Comment by jwpwh** [comment]
The short answer was expected. The long answer was expected. The question as to whether a separate build system could be used with static libraries as well as dynamic was tactfully asked and was just a head-slapping and why didn't I think of that moment.

Thank you.

**Comment by garethsb-sony** [comment]
🙂 I'm happy to have your thoughts on this, and would love to hear how you get on!
