### ISSUE TITLE
Setup dev environment Linux

### ISSUE THREAD

**Issue by desimetallica** [sony/nmos-cpp#174]
Hello I'm working on ubuntu 18.04 I'm trying to setup an environment  with this project. 
I've created the cmake project for eclipse with (with conan dep manager):

cd nmos-cpp/
mkdir Build
cd Build
cmake ../Development -G "Eclipse CDT4 - Unix Makefiles" -DCMAKE_BUILD_TYPE:STRING=DEBUG
Eclipse import -> make project

The project compile and runs but i've a lot of semantic error, I suppose is due to indexer but I don't know how to fix this...
Do you have any suggestion? Or specific setup to develop under linux environment? 
Many thanks for your help

**Comment by garethsb-sony** [comment]
I'm sorry, I do not use Eclipse so I cannot answer this question from experience. This post looks relevant: https://stackoverflow.com/questions/8148235/eclipse-cdt-shows-semantic-errors-but-compilation-is-ok 

Otherwise, maybe other nmos-cpp users will be able to help.

**Comment by desimetallica** [comment]
Thanks, I've already tried some fix but it looks too tricky, maybe i can try some different setup, which setup you suggest on linux?

**Comment by garethsb-sony** [comment]
See #95 for comments from a couple of other users. I tend to build and run unit tests and API tests on Linux (also run by GitHub Actions CI) but develop and debug using Visual Studio tools.

**Comment by desimetallica** [comment]
Many thanks for the link Gareth, in medio stat virtus, i've found a solution with code-insiders + cmake tools + gdb that for now is ok for me. I give a try to this solution before switch to visual studio + windows server 2019. Many thanks for the support! :)

**Comment by garethsb-sony** [comment]
Thanks so much for reporting back. I've heard positive things about the Visual Studio Code experience with GDB on Linux and also with Windows Subsystem for Linux. Good luck with your project.

P.S. And thanks for teaching me a useful Latin phrase I hadn't come across before! :-)
