### ISSUE TITLE
IS-04 Node API test_05 fail

### ISSUE THREAD

**Issue by TobiasThierolf** [sony/nmos-cpp#196]
Hello,

recently I've encountered an issue where an nmos registry was not able to detect our device. The nmos component was producing the message "Registration heartbeat error: 301 Moved Permanently.". 

Since this is just a warning I was not sure if it is actually causing the problem. Then I've started the investigation and started by running the IS-04 Node API test suite and test_05 "Node maintains itself in the registry via periodic calls to the health resource" failed with the error message "Heartbeats matched a different Node ID to the initial registration.". 

I put some log message into the code where the heartbeats are generated to see the Node ID that is used there and it is always the same. Then I compiled the nmos-node example application and run the same test which results in the exact same error message.

Then I updated the nmos-cpp and the nmos-testing repositories to the newest version but test_05 is still failing.

Right now I have no idea what is causing this, the only change I did on the nmos-cpp repository was to disable conan in the CMake files, but everything else is standard.

Thanks in advance
Tobias

**Comment by garethsb** [comment]
> running the IS-04 Node API test suite and test_05 "Node maintains itself in the registry via periodic calls to the health resource" failed with the error message "Heartbeats matched a different Node ID to the initial registration.".

The most common reason for this is that there really is another node somewhere on your network that is talking to the mock Registry started by the test suite.

**Comment by garethsb** [comment]
> I've encountered an issue where an nmos registry was not able to detect our device. The nmos component was producing the message "Registration heartbeat error: 301 Moved Permanently.".
> 
> Since this is just a warning I was not sure if it is actually causing the problem.

This is interesting... nmos-cpp makes these `POST` requests to the health endpoint without a trailing slash as per [URLs: Approach to Trailing Slashes - `POST` requests](https://specs.amwa.tv/is-04/releases/v1.3.1/docs/2.0._APIs.html#all-other-requests-put-post-delete-options-etc). Seeing this message probably means the Registry did not 'accept' the heartbeat which explains your experience. Based on the spec, I think the Registry is at fault.

Unfortunately, I think that [**IS-04-02 test_30**](https://github.com/AMWA-TV/nmos-testing/blob/master/nmostesting/suites/IS0402Test.py#L1812) won't have caught this issue, because [`do_request`](https://github.com/AMWA-TV/nmos-testing/blob/master/nmostesting/TestHelper.py#L165) does redirects.

**Comment by TobiasThierolf** [comment]
> > running the IS-04 Node API test suite and test_05 "Node maintains itself in the registry via periodic calls to the health resource" failed with the error message "Heartbeats matched a different Node ID to the initial registration.".
> 
> The most common reason for this is that there really is another node somewhere on your network that is talking to the mock Registry started by the test suite.

Ok I can check this by running the nmos-node and the test on the same machine without any other device within the same network.



> > I've encountered an issue where an nmos registry was not able to detect our device. The nmos component was producing the message "Registration heartbeat error: 301 Moved Permanently.".
> > Since this is just a warning I was not sure if it is actually causing the problem.
> 
> This is interesting... nmos-cpp makes these `POST` requests to the health endpoint without a trailing slash as per [URLs: Approach to Trailing Slashes - `POST` requests](https://specs.amwa.tv/is-04/releases/v1.3.1/docs/2.0._APIs.html#all-other-requests-put-post-delete-options-etc). Seeing this message probably means the Registry did not 'accept' the heartbeat which explains your experience. Based on the spec, I think the Registry is at fault.
> 
> Unfortunately, I think that [**IS-04-02 test_30**](https://github.com/AMWA-TV/nmos-testing/blob/master/nmostesting/suites/IS0402Test.py#L1812) won't have caught this issue, because [`do_request`](https://github.com/AMWA-TV/nmos-testing/blob/master/nmostesting/TestHelper.py#L165) does redirects.
> ( @peterbrightwell)

I will ask the about more details about how they expect the heartbeat message.

I will keep you updated! Thanks

**Comment by TobiasThierolf** [comment]
> > running the IS-04 Node API test suite and test_05 "Node maintains itself in the registry via periodic calls to the health resource" failed with the error message "Heartbeats matched a different Node ID to the initial registration.".
> 
> The most common reason for this is that there really is another node somewhere on your network that is talking to the mock Registry started by the test suite.

Perfect explanation! Worked immediately without other devices on the same network.

**Comment by TobiasThierolf** [comment]
> > I've encountered an issue where an nmos registry was not able to detect our device. The nmos component was producing the message "Registration heartbeat error: 301 Moved Permanently.".
> > Since this is just a warning I was not sure if it is actually causing the problem.
> 
> This is interesting... nmos-cpp makes these `POST` requests to the health endpoint without a trailing slash as per [URLs: Approach to Trailing Slashes - `POST` requests](https://specs.amwa.tv/is-04/releases/v1.3.1/docs/2.0._APIs.html#all-other-requests-put-post-delete-options-etc). Seeing this message probably means the Registry did not 'accept' the heartbeat which explains your experience. Based on the spec, I think the Registry is at fault.
> 
> Unfortunately, I think that [**IS-04-02 test_30**](https://github.com/AMWA-TV/nmos-testing/blob/master/nmostesting/suites/IS0402Test.py#L1812) won't have caught this issue, because [`do_request`](https://github.com/AMWA-TV/nmos-testing/blob/master/nmostesting/TestHelper.py#L165) does redirects.
> ( @peterbrightwell)

Perfect explanation as well. I just received a message from the registry provider and they expect a trailing slash. Since they don't follow the AMWA specification the Registry is at fault as already stated here.

Thank you for your help,
Tobias

**Comment by garethsb** [comment]
Thanks, @TobiasThierolf, I've opened https://github.com/AMWA-TV/nmos-testing/issues/615 to check this in the testing tool.
