### ISSUE TITLE
Race between new registrations and threads updating the model

### ISSUE THREAD

**Issue by billt-hlit** [sony/nmos-cpp#20]
I mentioned seeing this problem in Wuppertal -- not all devices are getting registered at start-up, although changing the log level seemed to help. I've been seeing this problem more frequently now and have started trying to investigate it. As best I can tell, there seems to be some sort of strange race between my threads adding things to the model and the thread that registers resources with the RDS.

To quickly summarize my system, my version of nmos-cpp-node has to interact with a server to discover devices and their associated resources to register them. The server typically has four devices (two transmitters and two receivers). Often, what happens is that only the first device to get added to the model, one of the transmitterts gets recorded with the RDS.

However, just to confuse the issue, if I run my software under valgrind (which forces everything to run single-threaded), then I only see one or both of the receivers get registered.

I've manage to work around the problem to some extent: If I delay the call to node_condition.notify_all() until after all four of a server's devices have been added to the model, then all the devices get registered with the RDS. However, if multiple servers get contacted in parallel, then I also have to make sure that the four servers' threads are started at least one second apart to make sure that all of each servers' devices get registered. However, this is all very much papering over the problem -- if events from the server arrive all together (like, say, from a bulk configure request), it's likely that the race will recur and some of the model updates won't make it to the RDS.

I realize this is a rather vague description of the problem, but I haven't any luck reproducing this problem with synthetic device data. If someone can suggest how I might investigate the problem, I'd really appreciate. In particular, I assume that the problem is somewhere in the registered_operation function, although the function looks to me like it has all the necessary locking. I don't fully understand how and  where the update time for the grain used to monitor update times come from -- for instance, if that time gets captured when the condition variable is first notified, and then the model gets updated while request_registration is waiting for an HTTP response, could the grain update times somehow off, causing registered_operation to think that updates that occurred during the registration_request call to be considered to have occurred before the registration?

Also, I notice that registered_operation sets most_recent_update twice, once before processing all the events and once afterwards. It seems to me that one of those updates is unnecessary at best and erroneous at worst. Doesn't the second update make it lose any changes to the grain that occurred while requests to the RDS were outstanding?

Thanks,
Bill

**Comment by billt-hlit** [comment]
After that long-winded description, it looks like changing the code to get the grain update time before fetching any queued events fixes the problem:
```
--- Development/nmos/node_behaviour.cpp
+++ Development/nmos/node_behaviour.cpp
@@ -846,9 +846,8 @@ namespace nmos
                 }
 
                 events = web::json::value::array();
-                node_behaviour_grain_guard guard(model.resources, grain, events);
-
                 most_recent_update = grain->updated;
+                node_behaviour_grain_guard guard(model.resources, grain, events);
 
                 while (0 != events.size())
                 {
@@ -899,8 +898,6 @@ namespace nmos
                     // wait for the request because interactions with the Registration API /resource endpoint must be sequential
                     condition.wait(lock, [&]{ return shutdown || registration_service_error || node_unregistered || request.is_done(); });
                 }
-
-                most_recent_update = grain->updated;
             }
 
             cancellation_source.cancel();

```

**Comment by billt-hlit** [comment]
On further inspection, the first half of that patch is problematic. For reasons that I don't understand, it breaks PATCH request handling. So, I just need to remove the second assignment to `most_recent_update`.

**Comment by garethsb-sony** [comment]
Thanks for the thorough investigation, Bill. I'll examine this more closely when I get back to the office but I think the original flaw was that I hadn't accounted for the ``condition.wait`` releasing the lock. Thus your ultimate suggestion is a very plausible fix.

**Comment by garethsb-sony** [comment]
@billt-hlit Thanks again for reporting and helping fix this. Sorry for the delay to merge, it took me a while to reproduce the issue within the example nmos-cpp-node app, but I think the ``nmos::experimental::node_resources_thread`` I've ended up with is also a slightly more useful stub for those setting out on making their own nodes.
