### ISSUE TITLE
Badges are out of date!

### ISSUE THREAD

**Issue by garethsb** [sony/nmos-cpp#214]
For some reason the badges for [build-test #297](https://github.com/sony/nmos-cpp/actions/runs/1367671562) for https://github.com/sony/nmos-cpp/commit/95536ae32341046dabf66286b373d70e97e3a59a have got lost, and the badges shown on the _README.md_ actually reflect the previous commit. I cannot understand from the logs for the above **build-test** run why that is.

Those badges would have shown that all the tests FAILED because the Ubuntu 18.04 and 20.04 builds of nmos-cpp-node all seg faulted. :-(

**Comment by jonathan-r-thorpe** [comment]
!!!!!

**Comment by garethsb** [comment]
This issue doesn't seem to have reoccurred, so closing...
