### ISSUE TITLE
Are subscription values not getting updated in the Query implementation?

### ISSUE THREAD

**Issue by VentuzVictor** [sony/nmos-cpp#216]
Hi!

We are testing the implementation of an IS-04 (v1.3) node, for that we use the "sony/nmos-cpp" for the registration and query and the  "sony /nmos-js"  for the GUI.

Under the `localhost:3000/senders` page we can access all registered senders, 
by clicking the switch button from one, for example the one with id:` dc3d6d15-af58-5d08-8a79-f919ecd367f4` which is "activated" (i.e. the change button is blue), A PATCH with the following JSON is performed:

```
{
  "transport_params": [
    {},
    {}
  ],
  "activation": {
    "mode": "activate_immediate".
  },
  "master_enable": false
}
```

That is, only the `master_enabled `is turned off, which also changes the subscription (`active `will be `false` and `receiver_id` will be `null`).

And so it happens:

IS-04 Node Endpoint: "node/v1.3/senders/dc3d6d15-af58-5d08-8a79-f919ecd367f4" Endpoint returns:

```
    "subscription": {
      "receiver_id": null,
      "active": false
    }
```

IS-05 "single/senders/dc3d6d15-af58-5d08-8a79-f919ecd367f4/active" returns:

```
  "master_enable": false,
  "receiver_id": "ac0dbb4b-a4a6-486c-98d6-1703c39276e1"
```
However, the IS-04 Query Endpoint "query/v1.3/senders/dc3d6d15-af58-5d08-8a79-f919ecd367f4" still returns subscription as true:

```
"subscription": {

    "active": true,
    "receiver_id": "ac0dbb4b-a4a6-486c-98d6-1703c39276e1"

}
```

In the GUI the error is not recognized then because the switch button appears as off, this may be due to an error in the state inside React?

However, when refreshing the page you can notice that the button switch returns to `true` by the values it gets from the response of the Query Endpoint.

Is this generally expected? I can't find any documentation on this.

Greetings and thanks in advance.

**Comment by garethsb** [comment]
It's the responsibility of the Node to send a registration update for the IS-04 Sender resource to the Registry.

Is the Node itself implemented with nmos-cpp? It should take care of this automatically.

**Comment by VentuzVictor** [comment]
Thanks for the Response.

Through which endpoint?

Could you please show me where in the docu is that specified? Maybe I skipped that 🙂

It's an own Implementation.

**Comment by garethsb** [comment]
The Node should do another `POST` to the same endpoint on the Registration API, but this time it will get a `200 OK` response rather than `201 Created`.

https://specs.amwa.tv/is-04/releases/v1.3.1/APIs/RegistrationAPI.html#http-status-code-200-2

The Node must send an update to the Registry whenever any of its IS-04 resources change. And if any resource attribute is modified it must also update the resource `version` attribute.

https://specs.amwa.tv/is-04/releases/v1.3.1/docs/2.1._APIs_-_Common_Keys.html#version

An IS-05 activation should update the IS-04 resource `version` even if no other attribute needs to be updated, e.g. even on reactivating with exactly the same parameters.

**Comment by VentuzVictor** [comment]
Ok, thanks for the clarification.

Since the node is responsible for doing this update, I was expecting to find this information in the documentation (for example where the version increment is mentioned) not in the Registration API specification.

**Comment by garethsb** [comment]
I completely agree, there ought to be a section in the docs, probably in **Behaviour: Registration** but with links from **Behaviour: Nodes** and the `version` docs. I've raised this, will look at it for a v1.3.x editorial patch.

**Comment by garethsb** [comment]
Added https://github.com/AMWA-TV/nmos-discovery-registration/issues/177. @jonathan-r-thorpe you can probably close this issue therefore.
