### ISSUE TITLE
IS-05 requests for modifying resources settings

### ISSUE THREAD

**Issue by massis08** [sony/nmos-cpp#234]
Hi! 
Me and @diegonunes4 work at @bisect-pt, and we are working on IS-05 requests and have a few questions.

We have already figured out that the IS-05 request for activating, for example, a sender, triggers the activation handler (the  
`nmos::connection_activation_handler make_node_implementation_connection_activation_handler(nmos::node_model& model, slog::base_gate& gate)`), that is responsible for activating resources at the correct time.

But, we can't seen to understand what handler or callback is triggered when making an IS-05 request for modifying settings for a sender or a receiver. 
If anyone can give some guidance on this matter. Thank you!

**Comment by garethsb** [comment]
The other relevant callbacks for IS-05 are these ones demonstrated in the example app:

https://github.com/sony/nmos-cpp/blob/46750381f33d19ce6b12a2f760db2f2f5faf2818/Development/nmos-cpp-node/node_implementation.cpp#L1231-L1234

* The transport file parser is used when a `"transport_file"` is included in a PATCH to a Receiver. This is the first chance for the application to reject the IS-05 request.
* The patch validator is called for both Senders and Receivers after the library has merged the PATCH transport parameters (and parsed transport file for Receivers) with the current contents of _/staged_. This is the last chance for the application to reject simple stage requests and scheduled activation requests.
* The auto resolver is called for both Senders and Receivers when an activation occurs (either immediately or scheduled) to convert any staged `"auto"` values. The application can reject the activation at this point, but of course the error can only be reported to the caller if it was an immediate activation.
* Then, for Senders, the transport file setter is called to update the _/transportfile_ endpoint based on the fully resolved _/active_ parameters.
* Then, finally, for both Senders and Receivers, the activation handler is called to trigger the change to the underlying sender/receiver to be applied.

Hope that helps... there ought to be a sequence diagram in the docs, for sure.

**Comment by massis08** [comment]
Thank you very much for your guidance @garethsb! 
Throughout this week, we were able to understand the flow of the callbacks when an IS-05 request is made. So now we can see some feedback in ours application when a request is made for modifying the settings of a sender or a receiver.
