### ISSUE TITLE
set cors in response

### ISSUE THREAD

**Issue by desimetallica** [sony/nmos-cpp#237]
Hello,
I'm moving forward with a special implementation for camera control based on this code.
I'm stuck on CORS i'm trying to setup CORS with:

`res.headers().add(U("Access-Control-Allow-Origin"), U("*"))`

But I'm still get blocked by my browser, should I set also the preflight in my res ?
THanks in advance for any help

**Comment by desimetallica** [comment]
I've solved with supporting the OPTIONS request in the right way:
 extra_listener.support(web::http::methods::OPTIONS,[](web::http::http_request req){
        web::http::http_response response(web::http::status_codes::OK);
        response.headers().add(U("Allow"), U("PATCH, POST, OPTIONS"));
        response.headers().add(U("Access-Control-Allow-Origin"), U("*"));
        response.headers().add(U("Access-Control-Allow-Methods"), U("PATCH, POST, OPTIONS"));
        response.headers().add(U("Access-Control-Allow-Headers"), U("Content-Type"));
        req.reply(response);
    });

The problem was the preflight request.

**Comment by garethsb** [comment]
Glad you made it work. FYI, _nmos/api_utils.cpp_ has the code used for all the NMOS APIs to create CORS preflight responses for `OPTIONS` and to add CORS headers to other responses.

**Comment by garethsb** [comment]
Also, _cpprest/http_utils.h_ has the constants for the CORS header names and some lower-level CORS helper functions.

**Comment by desimetallica** [comment]
Many thanks for the fast reply Gareth, I will try to refactor the code next! I see something on nmos::details useful indeed :)
