### ISSUE TITLE
How to deal with real media file and real media device?

### ISSUE THREAD

**Issue by soutaroumaejima** [sony/nmos-cpp#27]
I want to implement that sending and receiveing video file captured by device which is connected to real host machine according to media transport protocol between sender and receiver of virtual node.

Current open nmos-cpp application of node and registry implements communication between node and registry that send/receive virtual informations of device, media and so on.
Now then, does nmos-cpp application have function to deal with real device(e.g. USB Web camera) and send/receive real media file(e.g. H.264 video) according to media transport protocol(e.g. RTP) ?

If there were such functions, what action or editing of source code is necessary to use such functions?

**Comment by garethsb-sony** [comment]
nmos-cpp is focused very much on the implementation of the REST APIs of the NMOS specifications, and the behaviour of and interaction between NMOS nodes, registries and clients (e.g. broadcast controller) via these REST APIs. The [AMWA IS-05 Device Connection Management Specification](https://github.com/AMWA-TV/nmos-device-connection-management/tree/v1.0.x) defines the Connection API for setup of video/audio/data connections between senders and receivers. The nmos-cpp implementation of this part of NMOS is incomplete but several of us are working on it. (There are two pull requests in this area, see PR #22 and PR #23, but I cannot yet say the final form this work will take).

However, the implementation of video/audio/data streaming via RTP itself is currently outside the scope of nmos-cpp.

I hope that makes sense.

**Comment by soutaroumaejima** [comment]
`However, the implementation of video/audio/data streaming via RTP itself is currently outside the scope of nmos-cpp.`
OK, I see.

The nmos-cpp implementation of this part of NMOS is incomplete but several of us are working on it. (There are two pull requests in this area, see PR #22#22, Handle IS-05 GET requests. and PR #23#23, Handle IS-05 PATCH requests, but I cannot yet say the final form this work will take).

**Comment by soutaroumaejima** [comment]
`However, the implementation of video/audio/data streaming via RTP itself is currently outside the scope of nmos-cpp.`
OK, I see.

The nmos-cpp implementation of this part of NMOS is incomplete but several of us are working on it. (There are two pull requests in this area, see PR #22#22, Handle IS-05 GET requests. and PR #23#23, Handle IS-05 PATCH requests, but I cannot yet say the final form this work will take).

**Comment by soutaroumaejima** [comment]
> However, the implementation of video/audio/data streaming via RTP itself is currently outside the scope of nmos-cpp.

OK, I see. 
But, hearing this has made me to want to ask new question.

The question is whether or not current node/registry application of nmos-cpp is able to send/receive real JSON file as API and transportfile (e.g. SDP file)?
In order to confirm it, I tried to capture packet flowing between node and registry. However, it went wrong…
So I don’t know that whether current nmos-cpp has such function or not.

But, as you say, nmos-cpp succeeded in implementing functions of IS-05 GET and PATCH requests. So I think that nmos-cpp maybe has such function now.

If answer of this question was “Yes”, I want to know how to apply original JSON as API and SDP file to nmos-cpp in order to send/receive those between node and registry.

Sorry If I if my statement was besides the point or I didn’t make sense.

**Comment by garethsb-sony** [comment]
SDP files are sent/received in NMOS only by nodes and clients (i.e. not registry) using the IS-05 Connection API. In the master branch, the Connection API /transportfile endpoint is currently a stub/example.

On the other hand, JSON is used in the IS-04 Node API, Registration API and Query API to send/receive the NMOS resources, which are fully implemented in nmos-cpp.

The nmos-cpp-registry can handle interactions with many different kinds of nodes.

The nmos-cpp-node application demonstrates one way to set up a node's resources; see ``node_resources_thread`` in nmos/node_resources.cpp.

In your own node, you'll want to create the appropriate NMOS resources for the devices, senders, receivers, etc. that your node has.

**Comment by soutaroumaejima** [comment]
> SDP files are sent/received in NMOS only by nodes and clients (i.e. not registry) using the IS-05 Connection API.

Sorry, I had forget that point.
I understand that SDP file is prepared as imitation (I confirmed that fact by access to generated URL) but the function to send and receive it by HTTP between sender and receiver is not implemented at least now.

> On the other hand, JSON is used in the IS-04 Node API, Registration API and Query API to send/receive the NMOS resources, which are fully implemented in nmos-cpp.

OK, I see.
I could confirm that some JSON file’s were sent from node to registry using HTTP POST method by starting over capture of packet correctly at yesterday.

> The nmos-cpp-node application demonstrates one way to set up a node's resources; see node_resources_thread in nmos/node_resources.cpp.

OK, I tried to edit JSON file according to your advice.
If I have any problem about it, I might have to contact you again.
Thank you in advance.

**Comment by garethsb-sony** [comment]
> the function to send and receive it by HTTP between sender and receiver is not implemented at least now.

Receive is not implemented yet in master, but send is not the job of an NMOS node, it's the job of an NMOS client, such as a broadcast controller. The client requests the SDP file from the sender and then includes it in request to receiver. There are some open source NMOS clients, e.g. see https://github.com/sony/nmos-js.

**Comment by garethsb-sony** [comment]
> OK, I tried to edit some JSON files according to your advice.

Do you mean you changed the code that constructs the in-memory ``nmos::resource::data``, or have you made your own nmos-cpp node that reads the resources from JSON files? Or are you using a different NMOS Node implementation? Or are you just sending JSON to the registry using e.g. ``curl`` to test?

**Comment by soutaroumaejima** [comment]
> Receive is not implemented yet in master, but send is not the job of an NMOS node, it's the job of an NMOS client, such as a broadcast controller. The client requests the SDP file from the sender and then includes it in request to receiver.

私の理解不足で申し訳ありません，IS-05のテクニカルオーバービューを見直して，ようやく理解できたと思います．
あなたの話を解釈すると，現在はnmos-jsでSDPファイルをクライアントからノード内のセンダーにリクエストし，入手することは可能ですが，そのSDPファイルをレシーバーに送ることができない，ということであっていますか？

**Comment by soutaroumaejima** [comment]
> Do you mean you changed the code that constructs the in-memory nmos::resource::data, or have you made your own nmos-cpp node that reads the resources from JSON files? Or are you using a different NMOS Node implementation? Or are you just sending JSON to the registry using e.g. curl to test?

I’m sorry to have confused you.  My linguistic representation was wrong.
It was correct that “I will try to edit JSON files”.

What I’m going to do is addition new JSON file to some items (e.g. JSON files) sent from node to registry by HTTP now.
If it is realized, I will make new nmos-cpp node that reads the resources from JSON files.

However, since I have not enough read all code, I still don’t know which code is necessary to edit for that.

**Comment by garethsb-sony** [comment]
> What I’m going to do is addition new JSON file to some items (e.g. JSON files) sent from node to registry by HTTP now.
> If it is realized, I will make new nmos-cpp node that reads the resources from JSON files.
>
> However, since I have not enough read all code, I still don’t know which code is necessary to edit for that.

Reading the JSON from files _could_ be the right approach. _Or_ you can make the new JSON "files" programmatically (because they don't need to exist as files) quite simply just by modifying the ``node_resources_thread`` and modifying or reusing functions like ``make_sender`` in [nmos/node_resources.cpp](https://github.com/sony/nmos-cpp/blob/master/Development/nmos/node_resources.cpp).

Good luck.

**Comment by soutaroumaejima** [comment]
I could edit JSON file by edit function(i.e. `make_sender`) which is sent/received between node and registry.

However,

**Comment by garethsb-sony** [comment]
I'm sorry, I am having a hard time understanding what you are trying to do.

In order to populate the Node API with different/more resources than the examples in ``node_resources_thread`` of nmos-cpp-node, just modify that code. The different information will then be sent to the registry.

I am not sure why you mention nmos/type.h, because the list of NMOS Resource Types is fixed by the NMOS specification.

**Comment by soutaroumaejima** [comment]
I apologize for any confusion.

What I am trying to do is sending/receiving multiple JSON files about resources that are same type but little different.(e.g. there are two different senders and I want to send JSON files of these)
To achieve it, I had thought that creation of new function like `make_sender `and declaration of new type for it(that is the reason I refered to `type.h`) has been necessary.
However, thanks to you, I understood that such operation is not necessary and modification node_resources_thread(e.g. `insert_resource_after`) enables me to achieve populate the Node API with different/more resources as you said.

I am sorry for asking such strange questions…

**Comment by garethsb-sony** [comment]
> What I am trying to do is sending/receiving multiple JSON files about resources that are same type but little different.(e.g. there are two different senders and I want to send JSON files of these)

Ah! It would have been easier for you if ``node_resources_thread`` demonstrated creating more than one resource of some of the types, sorry! I'll modify the example that way.

**Comment by soutaroumaejima** [comment]
OK! Thank you for your quick and polite response!

**Comment by soutaroumaejima** [comment]
Hi. I haven't seen you for a long time.

I have a question which is same to what I previously asked. `nmos-cpp-node` are set to have each one of resources (ex: `receiver`, `sender` etc). I want to know how to add same kind of resource(e.g. there are two different senders and I want to send JSON files of these).

I understand that `make_sender` in `nmos_resources.cpp` defines elements of JSON.
Thanks to your answer, I understand that JSON files is inserted by function of `insert_resource_after` in `nmos_resources.cpp`.

So I thought that addition of `insert_resource_after` is necessary in order to add another resource as shown in here. However, such code didn't generates another receiver.
<details>
<summary>example of addition of insert_resource_after</summary>
<pre>
<code>
insert_resource_after(delay_millis, make_video_receiver(receiver_id, device_id,　nmos::transports::rtp_mcast, {}, model.settings), gate);
insert_resource_after(delay_millis, make_video_receiver(sender_id, device_id,　nmos::transports::rtp_mcast, {}, model.settings), gate);
</code>
</pre>
</details>

Sorry to ask such a basic question. If you could answer it, that would be great.

**Comment by garethsb-sony** [comment]
> So I thought that addition of insert_resource_after is necessary in order to add another resource as shown in here. However, such operation couldn't generate another resource.

Each unique resource needs a unique ID. In your example you show adding a second video receiver but using the unique ID already used for the sender???

If you don't care about repeatable ID, it should be very easy:

```C++
for (int i = 0; i < 10; ++i)
{
    auto receiver_id_i = make_id();
    insert_resource_after(delay_millis,
        make_video_receiver(receiver_id_i, device_id, nmos::transports::rtp_mcast, {}, model.settings),
        gate);
}
```

If you want repeatable unique ID, the example suggests generating them using unique names like "/x-nmos/node/receiver/0", so you might want to do something like this:

```C++
auto receiver_id_i = nmos::make_repeatable_id(seed_id, U("/x-nmos/node/receiver/") + utility::ostringstreamed(i));
```

**Comment by soutaroumaejima** [comment]
Hi. Please bear with me for asking so many times but　I have a new question about receiver/sender's `staged parameter` of IS-05.

I want to add new item to receiver/sender's `staged parameter` of JSON.
For example, adding new main item of JSON (such as `trasnport_file`, `transport_parameter`) or new sub item of JSON included to a main one(such as `rtp_enabled` parameter of `transport_parameter`).

Thanks to you, I can add new resource and item of JSON for IS-04 by adding new `value` to `data` for `make_sender` function of `node_resources.cpp` and so on. 

But, I can't add new item of JSON of connection API(IS-05).
I think that it's JSON is defined by `make_connection_resource_core`, `make_connection_receiver` of `node_resources.cpp` and so on.
But, in such functions, adding new item maybe isn't allowed freely by something like constraint condition.

If you know easy way to add new item of JSON for connection API, please let me know it.
I'm sorry for your inconvenience.

**Comment by garethsb-sony** [comment]
I don't understand what you think the difference is between (a) modifying JSON data of IS-04 ``nmos::resource``, (b) modifying JSON data of IS-05 ``nmos::resource``. In both cases, it's possible and you should stick to the relevant JSON Schema for each part of the JSON data.

In the case of IS-04 ``nmos::resource`` the top-level data may be validated by an IS-04 schema.

As the IS-05 ``nmos::resource`` top-level data combines the constraints, staged, active and transportfile endpoints, as described at https://github.com/sony/nmos-cpp/blob/master/Development/nmos/model.h#L93-L108, each of those fields has its own schema. As you say, staged and active transport parameters should also meet the constraints. We have a placeholder to implement vaidation against constraints, https://github.com/sony/nmos-cpp/blob/master/Development/nmos/connection_api.cpp#L89-L94. We intend to implement this by converting IS-05 constraints into full JSON Schema, but it's not highest priority yet.

**Comment by soutaroumaejima** [comment]
Thank you for your quick courteous response.

OK.
To edit IS-04 resource, I should edit JSON Schema(e.g. `receiver_data.json`)  and `nmos::resource`. Also, to edit IS-05 resource, I should edit its own schema `nmos::resource`.
Is my understanding correct?

**Comment by garethsb-sony** [comment]
> To edit IS-04 resource, I should edit JSON Schema(e.g. ``receiver_data.json``) and ``nmos::resource``. Also, to edit IS-05 resource, I should edit its own schema ``nmos::resource``.
> Is my understanding correct?

No, absolutely do not edit the schemas, unless you want to be non-conforming to the NMOS specification.

**Comment by garethsb-sony** [comment]
You should not add proprietary data to the JSON except via the mechanisms allowed by the NMOS specification. For example "tags", "description" and "label" defined by ``resource_core.json`` in IS-04.

**Comment by garethsb-sony** [comment]
> ... for example, if I want to use another transport protocol...

Are you a member of AMWA? Joining the AMWA Networked Media Incubator is likely to be a better way to ask these kinds of questions.

There is a current proposal to add MQTT and WebSocket as transport protocols (to be used by IS-07 for event & tally information), but I am not aware of any activity to support other _media_ transports. The approach for IS-07 will probably update IS-05 with the ability to define extra transport parameters, but it's not finalised yet.

**Comment by soutaroumaejima** [comment]
> Are you a member of AMWA? Joining the AMWA Networked Media Incubator is likely to be a better way to ask these kinds of questions.

No, I'm not AMWA member. But you make me want to join AMWA Networked Media Incubator. 

> There is a current proposal to add MQTT and WebSocket as transport protocols (to be used by IS-07 for event & tally information), but I am not aware of any activity to support other media transports. The approach for IS-07 will probably update IS-05 with the ability to define extra transport parameters, but it's not finalised yet.

I thought that adding extra parameter to IS-04/05 is easy, however, I understood that it seems to be too difficult as you say. I am sorry for asking such strange questions. 

I will consider to joining AMWA. Thank you for prompt reply!

**Comment by garethsb-sony** [comment]
I think most questions raised in this issue have been addressed, so I am closing this issue. The open PR #35 is reminding me that ``nmos-cpp-node`` should serve as both a simulated Node for testing and as a demo of how a real Node can hook into the ``nmos-cpp`` implementation.

Thank you for your discussions, @soutaroumaejima.
