### ISSUE TITLE
Question about LLDP related kernel messages

### ISSUE THREAD

**Issue by TobiasThierolf** [sony/nmos-cpp#274]
Hello,

this is not really a bug or something serious, but we recently discovered some messages in the kernel log that we didn't really understand where they came from, until we could track it down to the LLDP implementation used in the nmos-cpp library. We are using a debian 11 operating system.

The messages are looking like this:
```
[   78.976558] Bluetooth: Core ver 2.22
[   78.976848] NET: Registered PF_BLUETOOTH protocol family
[   78.976850] Bluetooth: HCI device and connection manager initialized
[   78.976855] Bluetooth: HCI socket layer initialized
[   78.976857] Bluetooth: L2CAP socket layer initialized
[   78.976860] Bluetooth: SCO socket layer initialized
[   79.000495] device mlnx1 entered promiscuous mode
[   79.014880] device mlnx2 entered promiscuous mode
```

The messages regarding the promiscuous mode are clear, but for some reason the messages about bluetooth are showing up at the same time. There is no bluetooth device connected to our system and I checked the code interacting with the pcap library but I wasn't able to find any reference that could explain why this message shows up.

As I said there is no issue at all, so it is not really important if there is no answer to this question. We are just curios and try to understand what is happening on the system and why.

Thanks in advance,
Tobias Thierolf

**Comment by garethsb** [comment]
I haven't noticed that before... (Side story: I forgot to enable LLDP for our JT-NM Tested entry last month. 🤦‍♂️ Frustrating as could have passed all those tests too!)

If this is related to libpcap used in the minimal viable LLDP implementation that nmos-cpp has, perhaps you could disable the Bluetooth module in libpcap - https://github.com/the-tcpdump-group/libpcap/blob/dc14a7babca1471809bee6872539ff836937840e/CMakeLists.txt#L348

**Comment by TobiasThierolf** [comment]
Oh sorry to hear that you had some issues on the JT-NM :(

We are almost certain that it comes from pcap, we just compiled our components with LLDP disabled and these messages didn't appear in the logs anymore.

Thank you for the hint on how to disable the Bluetooth module in libpcap!
