### ISSUE TITLE
Does not work with cpprestsdk master right now

### ISSUE THREAD

**Issue by maweit** [sony/nmos-cpp#30]
Tried on 2018-09-20: nmos-cpp-node crashes after a couple of seconds with latest cpprestsdk. Version from May 18, 2018 works

**Comment by garethsb-sony** [comment]
@maweit Martin, we've tried several recent releases of C++ REST SDK, including v2.10.6 from 20 September 2018. I didn't find an immediate crash on any platform, but I did encounter a crash-on-exit bug with v2.10.6 on Windows depending on the CMake configuration options, e.g. ``CPPREST_PPLX_IMPL``, ``CPPREST_HTTP_LISTENER_IMPL`` and ``CPPREST_HTTP_CLIENT_IMPL``. This seems to have been resolved by the latest release, v2.10.8, so I have updated the documentation to suggest that version for now. If you were able to confirm that solves your issue, that would be great!
Thanks.

**Comment by garethsb-sony** [comment]
Ah, looks like the v2.10.8 tagged release may not work on some Linux environments. There's a fix on master, see https://github.com/Microsoft/cpprestsdk/commit/65267c6e83e7e29ed3bdddde13d2c4bbb10e1bff

**Comment by billt-hlit** [comment]
I also get a warning when building on that target:
> /home/hbv-bld1/bt/git/nmos-cpp/Development/nmos/sdp_utils.cpp: In function ?nmos::sdp_parameters nmos::get_session_description_sdp_parameters(const web::json::value&)?:
> /home/hbv-bld1/bt/git/nmos-cpp/Development/nmos/sdp_utils.cpp:823:83: warning: narrowing conversion of ?sdp::fields::clock_rate.web::json::field<T>::operator()<const web::json::value>((* & rtpmap_value))? from ?uint64_t {aka long unsigned int}? to ?param_type {aka long int}? inside { } [-Wnarrowing]
>              sdp_params.audio.sample_rate = nmos::rational{ sdp::fields::clock_rate(rtpmap_value) };
>                                                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~

**Comment by garethsb-sony** [comment]
Things look good to me with current cpprestsdk master, just [tagged v2.10.9](https://github.com/Microsoft/cpprestsdk/tree/v2.10.9).
I've run a few tests on both Linux and Windows.

Let's open a new issue if further problems arise.
