### ISSUE TITLE
Adding some quick ways of spinning up sources and flows with parents.

### ISSUE THREAD

**Issue by cristian-recoseanu** [sony/nmos-cpp#312]
Would it be possible to have a way of spinning up an nmos-cpp mock which can create sources and flows with parents?

It would be great for testing such scenarios with a Controller product for example.

Thanks!

**Comment by garethsb** [comment]
I've been thinking about this. I came up with the following graph construction, in which vertices represent signals (IS-04 Sources or Flows) and edges represent the `parent` relation.

I think it gives a good mix of numbers of children and parents per signal and length of ancestry in both directions.
* Half of all signals will have no children (incoming links), half of the rest only one, half of the rest two, etc.
* Half of all signals will have no parents (outgoing links), half of the rest only one, half of the rest two, etc.
* Half of all signals will have no ancestors, half of the rest only one generation of ancestors, half of the rest two generations, etc.
* Half of all signals will have no descendants, half of the rest only one generation, half of the rest two generations, etc.

![image](https://user-images.githubusercontent.com/31761158/205358459-0687f16b-5429-482b-9ed6-020793fdf3c7.png)

I've got an implementation in mind...
