### ISSUE TITLE
Compilation issue with "sdp_test" in nmos-cpp-registry-test right now

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-cpp#32]
This previously worked fine. Build fails at CMakeFiles/nmos-cpp-registry-test.dir/sdp/test/sdp_test.cpp.o with latest commit (specifically d6e9c49).

I've re-checked the dependencies and nothings seems to have changed. My detailed output from Docker Build is below:

> Step 7/10 : RUN mkdir /home/nmos-cpp/Development/build &&     cd /home/nmos-cpp/Development/build &&     cmake     -G "Unix Makefiles"     -DCMAKE_CONFIGURATION_TYPES:STRING="Debug;Release"     -DBoost_USE_STATIC_LIBS:BOOL="1"     -DBOOST_INCLUDEDIR:PATH="/home/boost_1_67_0"     -DBOOST_LIBRARYDIR:PATH="/home/boost_1_67_0/x64/lib"     -DWEBSOCKETPP_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp"     -DCPPREST_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/"     -build /home/nmos-cpp/Development/build .. &&     make
>  ---> Running in 20f9f7a5d33f
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
> -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
> -- Found cpprestsdk
> -- Using configured websocketpp include directory at /home/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Boost version: 1.67.0
> -- Found the following Boost libraries:
> --   system
> --   date_time
> --   regex
> --   thread
> --   chrono
> --   atomic
> -- Configuring done
> -- Generating done
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CMAKE_CONFIGURATION_TYPES
> 
> 
> -- Build files have been written to: /home/nmos-cpp/Development/build
> Scanning dependencies of target mdns_static
> [  1%] Building CXX object CMakeFiles/mdns_static.dir/mdns/core.cpp.o
> [  1%] Building CXX object CMakeFiles/mdns_static.dir/mdns/dns_sd_impl.cpp.o
> [  2%] Building CXX object CMakeFiles/mdns_static.dir/mdns/service_advertiser_impl.cpp.o
> [  2%] Building CXX object CMakeFiles/mdns_static.dir/mdns/service_discovery_impl.cpp.o
> /home/nmos-cpp/Development/mdns/service_discovery_impl.cpp: In function 'bool mdns_details::getaddrinfo(const address_handler&, const string&, uint32_t, const duration&, DNSServiceCancellationToken, slog::base_gate&)':
> /home/nmos-cpp/Development/mdns/service_discovery_impl.cpp:345:14: warning: unused variable 'more_coming' [-Wunused-variable]
>          bool more_coming = true;
>               ^
> [  3%] Linking CXX static library libmdns_static.a
> [  3%] Built target mdns_static
> Scanning dependencies of target nmos-cpp-registry-test
> [  3%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/nmos-cpp-registry/test/main.cpp.o
> [  4%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/api_router.cpp.o
> [  4%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/host_utils.cpp.o
> [  5%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/http_utils.cpp.o
> [  5%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/json_utils.cpp.o
> [  6%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/test/api_router_test.cpp.o
> [  6%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/test/http_utils_test.cpp.o
> [  7%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/test/json_utils_test.cpp.o
> [  7%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/cpprest/test/regex_utils_test.cpp.o
> [  8%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/mdns/test/core_test.cpp.o
> [  8%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/mdns/test/mdns_test.cpp.o
> [  9%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/nmos/api_utils.cpp.o
> [  9%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/nmos/test/api_utils_test.cpp.o
> [ 10%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/nmos/test/paging_utils_test.cpp.o
> [ 10%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/sdp/sdp_grammar.cpp.o
> [ 11%] Building CXX object CMakeFiles/nmos-cpp-registry-test.dir/sdp/test/sdp_test.cpp.o
> /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:97:40: warning: integer constant is so large that it is unsigned
>              { sdp::fields::session_id, 16088568667046861077 },
>                                         ^
> /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:98:45: warning: integer constant is so large that it is unsigned
>              { sdp::fields::session_version, 16088568667046861078 },
>                                              ^
> /home/nmos-cpp/Development/sdp/test/sdp_test.cpp: In function 'void ____C_A_T_C_H____T_E_S_T____0()':
> /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:102:22: error: conversion from '__int128' to 'const web::json::details::value_init' is ambiguous
>          }, keep_order) },
>                       ^
> In file included from /home/nmos-cpp/Development/sdp/json.h:5:0,
>                  from /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:5:
> /home/nmos-cpp/Development/cpprest/json_utils.h:231:30: note: candidate: web::json::details::value_init::value_init(int32_t)
>                  using value::value;
>                               ^
> /home/nmos-cpp/Development/cpprest/json_utils.h:231:30: note: candidate: web::json::details::value_init::value_init(uint32_t)
> /home/nmos-cpp/Development/cpprest/json_utils.h:231:30: note: candidate: web::json::details::value_init::value_init(int64_t)
> /home/nmos-cpp/Development/cpprest/json_utils.h:231:30: note: candidate: web::json::details::value_init::value_init(uint64_t)
> /home/nmos-cpp/Development/cpprest/json_utils.h:231:30: note: candidate: web::json::details::value_init::value_init(double)
> /home/nmos-cpp/Development/cpprest/json_utils.h:237:17: note: candidate: web::json::details::value_init::value_init(bool)
>                  value_init(bool b) : value(b) {}
>                  ^
> In file included from /usr/include/c++/5/bits/stl_algobase.h:64:0,
>                  from /usr/include/c++/5/memory:62,
>                  from /usr/local/include/cpprest/json.h:18,
>                  from /home/nmos-cpp/Development/sdp/sdp.h:4,
>                  from /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:2:
> /usr/include/c++/5/bits/stl_pair.h:133:12: note:   initializing argument 2 of 'constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&) [with _U1 = const web::json::field<long unsigned int>&; <template-parameter-2-2> = void; _T1 = std::__cxx11::basic_string<char>; _T2 = web::json::details::value_init]'
>   constexpr pair(_U1&& __x, const _T2& __y)
>             ^
> /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:250:18: error: no matching function for call to 'value_of(<brace-enclosed initializer list>, const bool&)'
>      }, keep_order);
>                   ^
> In file included from /home/nmos-cpp/Development/sdp/json.h:5:0,
>                  from /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:5:
> /home/nmos-cpp/Development/cpprest/json_utils.h:245:33: note: candidate: web::json::value web::json::value_of(std::initializer_list<std::pair<std::__cxx11::basic_string<char>, web::json::details::value_init> >, bool)
>          inline web::json::value value_of(std::initializer_list<std::pair<utility::string_t, web::json::details::value_init>> fields, bool keep_order = false)
>                                  ^
> /home/nmos-cpp/Development/cpprest/json_utils.h:245:33: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::initializer_list<std::pair<std::__cxx11::basic_string<char>, web::json::details::value_init> >'
> /home/nmos-cpp/Development/cpprest/json_utils.h:259:33: note: candidate: template<class> web::json::value web::json::value_of(std::initializer_list<web::json::details::value_init>)
>          inline web::json::value value_of(std::initializer_list<web::json::details::value_init> elements)
>                                  ^
> /home/nmos-cpp/Development/cpprest/json_utils.h:259:33: note:   template argument deduction/substitution failed:
> /home/nmos-cpp/Development/sdp/test/sdp_test.cpp:250:18: note:   cannot convert '{{sdp::fields::protocol_version, 0}, {sdp::fields::origin, <expression error>}, {sdp::fields::session_name, "Example Sender 1 (Video)"}, {sdp::fields::time_descriptions, web::json::value_of(std::initializer_list<web::json::details::value_init>) [with <template-parameter-1-1> = void]()}, {sdp::fields::attributes, web::json::value_of(std::initializer_list<web::json::details::value_init>) [with <template-parameter-1-1> = void]()}, {sdp::fields::media_descriptions, web::json::value_of(std::initializer_list<web::json::details::value_init>) [with <template-parameter-1-1> = void]()}}' (type '<brace-enclosed initializer list>') to type 'std::initializer_list<web::json::details::value_init>'
>      }, keep_order);
>                   ^
> make[2]: *** [CMakeFiles/nmos-cpp-registry-test.dir/sdp/test/sdp_test.cpp.o] Error 1
> make[1]: *** [CMakeFiles/nmos-cpp-registry-test.dir/all] Error 2
> make: *** [all] Error 2
> CMakeFiles/nmos-cpp-registry-test.dir/build.make:257: recipe for target 'CMakeFiles/nmos-cpp-registry-test.dir/sdp/test/sdp_test.cpp.o' failed
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nmos-cpp-registry-test.dir/all' failed
> Makefile:94: recipe for target 'all' failed
> The command '/bin/sh -c mkdir /home/nmos-cpp/Development/build &&     cd /home/nmos-cpp/Development/build &&     cmake     -G "Unix Makefiles"     -DCMAKE_CONFIGURATION_TYPES:STRING="Debug;Release"     -DBoost_USE_STATIC_LIBS:BOOL="1"     -DBOOST_INCLUDEDIR:PATH="/home/boost_1_67_0"     -DBOOST_LIBRARYDIR:PATH="/home/boost_1_67_0/x64/lib"     -DWEBSOCKETPP_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp"     -DCPPREST_INCLUDE_DIR:PATH="/home/cpprestsdk-2.10.2-nmos-cpp/"     -build /home/nmos-cpp/Development/build .. &&     make' returned a non-zero code: 2
> Makefile:9: recipe for target 'build' failed
> make: *** [build] Error 2

**Comment by garethsb-sony** [comment]
Thanks for the report, I checked for exactly this sort of problem when I made the change, but obviously not on enough compilers.

**Comment by garethsb-sony** [comment]
Hi, Rich. Hopefully that fixes things! Thanks, again.

**Comment by rhastie** [comment]
Thanks Gareth... Compilation now working with commit 8c36599
Much appreciated - Rich
