### ISSUE TITLE
Windows Build

### ISSUE THREAD

**Issue by emanueledimauro** [sony/nmos-cpp#322]
I used nmos-cpp in linux environment and it works perfectly. However, I tried compiling on windows and had problems with conan (old_conan_cmake_install). 

Has anyone compiled for windows yet ? Can I find a repository with the binaries ? 

I would be very curious to try !

**Comment by garethsb** [comment]
It's built on Windows in every GitHub Actions run, and Windows binaries are available in Conan Center Index. What is your problem?

**Comment by garethsb** [comment]
> Would you have a link where I can download them for OS Windows?

Last time I checked, these instructions worked to get Conan to install a prebuilt binary:  https://github.com/sony/nmos-cpp/issues/283#issuecomment-1302091773

**Comment by garethsb** [comment]
> I have this message :
> 
> ```
> ERROR: Error while parsing [options] in conanfile.txt
> ```

I wonder if this means you have Conan 2.0, as I believe the syntax of options changed slightly. We haven't quite completed the work to support Conan 2.0 so that's why we recommend `pip install conan=~1.47` for now.

**Comment by emanueledimauro** [comment]
Thanks, 
but 1.47 is not enough, I have this message : 

```
ERROR: nasm/2.15.05: Cannot load recipe.
Error loading conanfile at 'C:\Users\birun\.conan\data\nasm\2.15.05\_\_\export\conanfile.py': Current Conan version (1.53.0) does not satisfy the defined one (>=1.55.0).

``` 

I'll try with 1.55 !

**Comment by garethsb** [comment]
Sorry, yes - the nmos-cpp recipe itself only needs 1.47 or higher, but recipes for some of its dependencies may have been updated to require a higher version. Using `conan=~1.47` means it should install the highest version >= 1.47 < 2.0, but you need to add `--upgrade` if you already have one in this range to accommodate the newer dependency requirements.

**Comment by emanueledimauro** [comment]
It's ok !
Thank you very much for helping me !

**Comment by lo-simon** [comment]
Resolved
