### ISSUE TITLE
Allowed to register a flow without a valid source

### ISSUE THREAD

**Issue by VenkateswaranJ** [sony/nmos-cpp#355]
Registry allows to register IS-04 flow before registering a valid source. Basically, I can create a flow with some random source_id and register to the registry. Is it a valid case?

**Comment by lo-simon** [comment]
Yes it is allowed, but the nmos-cpp-registry must be configured with `"allow_invalid_resources": true`

**Comment by VenkateswaranJ** [comment]
But I can register flow without source even with `allow_invalid_resources": false`. I'm using the latest version of https://hub.docker.com/r/rhastie/nmos-cpp

**Comment by VenkateswaranJ** [comment]
I can register flow without source even in the [testbuild](https://hub.docker.com/layers/rhastie/nmos-cpp/testbuild/images/sha256-dc4737358003c6638a6af058555b9739691d8c0d882328a859a30083f86665d2?context=explore) (20 days older)

**Comment by garethsb** [comment]
@VenkateswaranJ is correct about the behaviour. This is the intentional design because the referencing model of IS-04 has the Device as the owner of the Flow (by the `device_id` reference to the former from the latter). Therefore nmos-cpp only requires the Device to be added before the Flow, not the Source. Other non-owner references are checked and reported in the nmos-cpp-registry logs but do not cause a registration request to be rejected.

**Comment by garethsb** [comment]
**Referential Integrity** rules for the Registration API are here: https://specs.amwa.tv/is-04/releases/v1.3.2/docs/Behaviour_-_Registration.html#referential-integrity

Note that the **Identity Hierarchy** and **Identifier Persistence & Generation** sections at https://specs.amwa.tv/is-04/releases/v1.3.2/docs/Data_Model_-_Identifier_Mapping.html are slightly out of date and confusing, the Architecture Review team have a backlog item to edit this page.

**Comment by garethsb** [comment]
The warning "Registration requested for flow: {flowId} from unknown source: {sourceId}" is generated in the log:

https://github.com/sony/nmos-cpp/blob/647d4b399dee2bdf7f4a1fe0c7f8bc5988db9828/Development/nmos/registration_api.cpp#L346-L356

**Comment by VenkateswaranJ** [comment]
Shall we close this issue?

**Comment by lo-simon** [comment]
Thank you @VenkateswaranJ for your request, as it has now been resolved, I am going to close this issue.
