### ISSUE TITLE
Can't discover registry

### ISSUE THREAD

**Issue by acresp** [sony/nmos-cpp#358]
Hello,

I'm trying to set up the nmos-cpp-registry and nmos-cpp-node
I also have some 2110 nmos IS-04 & IS-05 devices on the test network

For the moment, nothing is seen

I build the nmos-cpp suites and here is the log when I run the nmos-cpp-registry:

`*** WARNING *** The program 'nmos-cpp-node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'nmos-cpp-node' called 'DNSServiceCreateConnection()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>`

I suspect something misconfigured ?
The config.json is as follow:

`{
    "logging_level": -20,
    "domain": "local."
}
`

Also, when I run in parallel the nmos-cpp-node here is what I see in the logs:

`2023-12-05 11:59:42.036: warning: 140486534641216: Did not discover a suitable Registration API via DNS-SD
2023-12-05 11:59:42.036: warning: 140486509463104: Did not discover a suitable System API via DNS-SD
2023-12-05 11:59:43.036: info: 140486593390144: Attempting discovery of a Registration API in domain: .
2023-12-05 11:59:43.037: info: 140486769636928: Attempting discovery of a System API in domain: .`

I have also, on the same server, configured BIND9 following all the guide to configure the DNS-SD records.
I tested and I think it's correctly pointing to my registry server...

Also, nothing of the devices is seen anywhere, for my test purposes I have:

- 2* emSFP from embrionix (2110 MSA sfp to coax)
- 2* blackmagic 2110 3x3G converters

The goal is to make some routing 🙂 

Regards

**Comment by garethsb** [comment]
From the first log you included, we can see that it was actually the Node running, not the Registry?

> I build the nmos-cpp suites and here is the log when I run the nmos-cpp-registry:
> 
> `*** WARNING *** The program 'nmos-cpp-node' uses the Apple Bonjour compatibility layer of Avahi.`

**Comment by acresp** [comment]
> From the first log you included, we can see that it was actually the Node running, not the Registry?
> 
> > I build the nmos-cpp suites and here is the log when I run the nmos-cpp-registry:
> > `*** WARNING *** The program 'nmos-cpp-node' uses the Apple Bonjour compatibility layer of Avahi.`

Sorry, bad copy-paste, I have the same error when running the registry:

`*** WARNING *** The program 'nmos-cpp-registry' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'nmos-cpp-registry' called 'DNSServiceCreateConnection()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
2023-12-05 12:36:01.411: error: 140013433968192: DNSServiceCreateConnection reported error: -65544
*** WARNING *** The program 'nmos-cpp-registry' called 'DNSServiceCreateConnection()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
`

**Comment by garethsb** [comment]
Those warnings don't affect the correct functioning of the Registry or Node, so your problem is something else.

**Comment by acresp** [comment]
Didn't find the issue but I decided to switch on easy-nmos docker solutions, everything is fine now. Reg

**Comment by garethsb** [comment]
@acresp I've just noticed you said you set up BIND9 server - i.e. unicast DNS-SD - but you mentioned using domain `"local."` - which indicates multicast DNS-SD (mDNS).
