### ISSUE TITLE
GHS_TOOLSET_ROOT directory "/usr/ghs" does not exist.

### ISSUE THREAD

**Issue by BillClaghorn** [sony/nmos-cpp#365]
I found the problem, set generator to Unix Makefiles. 
• Hardware Platform (Ubuntu 22.04.3)

**Comment by BillClaghorn** [comment]
cat /home/bill/nmos-cpp/Development/CMakeFiles/CMakeOutput.log
The target system is: GHS-MULTI -  - 
The host system is: Linux - 6.5.0-15-generic - x86_64

**Comment by jonathan-r-thorpe** [comment]
Hi Bill - glad you found the problem. Can we close this issue?

**Comment by BillClaghorn** [comment]
Yes, you can close the issue.,

I had another issue. CMake wouldn’t Configure. It turns out that Conan was the latest version, 2.0.17.

I had to downgrade to Conan 1.59. Then everything worked.

sudo pip install conan==1.59
$ conan --version
Conan version 1.59.0



Bill Claghorn
VP Software Engineering
Advanced Systems Group, LLC
(510) 654-8300
***@***.******@***.***>
www.asgllc.com<http://www.asgllc.com/>

***@***.***

**Comment by lo-simon** [comment]
Hi Bill

Thank you for using `nmos-cpp` and good to hear you have got it working.

Yes, currently not supporting Conan 2, see https://github.com/sony/nmos-cpp/blob/master/Documents/Dependencies.md#conan
