### ISSUE TITLE
sdp connection info outside of media description not handled correctly

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#37]
In sdp_utils.cpp in get_session_description_sdp_parameters where the Connection Data is handled after the Time Descriptions, the code assumes that the connection_data, if there is any, is an array. Unfortunately, if there is connection data outside the media descriptions, it is stored as an object instead of an array and the connection_data.at(0) causes an exception. If the code is changed to access it as an object, the exception is avoided. (i.e. just changed connection_data.at(0) to connection_data)

Sample SDP: (note that the c= is not in a specific media description.)

v=0
o=- 16119794021444559877 16119794021444559877 IN IP4 192.168.87.25
s=wnip:BL07S01:Blade07c:7.0.0.1
i=BL07S01 : Blade07c
c=IN IP4 239.192.195.69/255
t=0 0
m=audio 50100 RTP/AVP 100
a=recvonly
a=rtpmap:100 L24/48000/2
a=fmtp:100 channel-order=SMPTE2110.(ST);
a=ptime:0.25
a=ts-refclk:ptp=IEEE1588-2008:00-00-00-00-00-00-00-00:4
a=mediaclk:direct=0

**Comment by garethsb-sony** [comment]
Thanks!
