### ISSUE TITLE
cant reach the webisite for the Node API

### ISSUE THREAD

**Issue by ibramatar07** [sony/nmos-cpp#381]
hello when i run the nmos-cpp-node and created the node and get the node API 

like 10.0.0.1:3212/node/v1.3

when i try to visit the link its gives me cant reach 

any help

**Comment by lo-simon** [comment]
Hi Ibrahim
What settings are you using to configure the nmos-cpp-node? Can you show us your node (console) log? The node API should be serving all the network interfaces.
Can you ping 10.0.0.1? This IP address looks like the default gateway IP!

**Comment by ibramatar07** [comment]
![Capture](https://github.com/sony/nmos-cpp/assets/56487964/fc71ac3e-1953-4db4-93cd-3ac8a5a6515d)

you can find a screenshot above, the node API, and i tried to ping the ip address in the console log (not the one mentioned in the question) and its looks good.


also when i try to run the nood using nmos testing tools its respond with no node API.

**Comment by ibramatar07** [comment]
its very similar to the one in the docs, its build the settings(cpprestsdk, websocket,...), also configure nmos-cpp with node api

only the warning is 

warning: Didcnot discover a suitable registration API via DNS-SD
and i think its not the reason because i was able to show the node controller(using node API) before but now i cant 

i tried to ping the ip address in the console log (not the one mentioned in the question) and its looks good.

also when i try to run the nood using nmos testing tools its respond with no node API.

**Comment by garethsb** [comment]
If you are building and running on Windows, with listener=httpsys as was shown in your screenshot, you need to run the program with Administrator privileges.

**Comment by lo-simon** [comment]
Please try @garethsb suggestion.

**Comment by ibramatar07** [comment]
thank you its work now
