### ISSUE TITLE
build failure with gcc 6.3 and boost 1.62

### ISSUE THREAD

**Issue by btrost-harmonicinc** [sony/nmos-cpp#42]
Commit ca4aca564e introduced a build problem under Debian 4.9:
> /home/hbv-bld1/bt/git/nmos-cpp/Development/cpprest/ws_listener_impl.cpp:227:103: error: no match for 'operator==' (operand types are 'boost::system::error_code' and 'std::error_code')
>                                  if (make_error_code(boost::asio::error::address_family_not_supported) == ec
>                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
> In file included from /usr/include/boost/asio/io_service.hpp:25:0,
>                  from /usr/include/boost/asio/basic_io_object.hpp:19,
>                  from /usr/include/boost/asio/basic_waitable_timer.hpp:20,
>                  from /usr/include/boost/asio/steady_timer.hpp:30,
>                  from /usr/include/websocketpp/common/asio.hpp:61,
>                  from /usr/include/websocketpp/transport/asio/base.hpp:31,
>                  from /usr/include/websocketpp/transport/asio/connection.hpp:31,
>                  from /usr/include/websocketpp/transport/asio/endpoint.hpp:32,
>                  from /usr/include/websocketpp/config/asio_no_tls.hpp:32,
>                  from /home/hbv-bld1/bt/git/nmos-cpp/Development/cpprest/ws_listener_impl.cpp:18:

...and similarly for the other two comparisons in that expression. I tried simply casting the LHS to the RHS's type and vice-versa, but gcc didn't like the casts.

Details:
*  Linux hbv-bld1 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
*  gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
*  BOOST_LIB_VERSION "1_62"
*  Built with "cmake   ..  -D'BUILD_SHARED_LIBS'='0'"

**Comment by billt-hlit** [comment]
I also get a warning building on that Debian system:
> /home/hbv-bld1/bt/git/nmos-cpp/Development/nmos/sdp_utils.cpp: In function ?nmos::sdp_parameters nmos::get_session_description_sdp_parameters(const web::json::value&)?:
> /home/hbv-bld1/bt/git/nmos-cpp/Development/nmos/sdp_utils.cpp:823:83: warning: narrowing conversion of ?sdp::fields::clock_rate.web::json::field<T>::operator()<const web::json::value>((* & rtpmap_value))? from ?uint64_t {aka long unsigned int}? to ?param_type {aka long int}? inside { } [-Wnarrowing]
>              sdp_params.audio.sample_rate = nmos::rational{ sdp::fields::clock_rate(rtpmap_value) };
>                                                             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
