### ISSUE TITLE
nmos-cpp-mode "is04_versions" setting does not affect DNS-SD advertisements

### ISSUE THREAD

**Issue by billt-hlit** [sony/nmos-cpp#47]
I'm trying out the latest code (to test those SDP parser changes) and noticed the is04_versions setting (I thought I would use it for now because I'm not sure what changes I would need to make to support v1.3 correctly). I notice that the mDNS advertisements for _nmos-node._tcp still claim the api_ver supports v1.2 even though I specified '"is04_versions": ["v1.0", "v1.1"]' on the command line. The HTTP interface correctly reflect the versions as exposed at /x-nmos/node/. Furthermore, the advertisements don't reflect that v1.3 is available if I omit the setting.

**Comment by garethsb-sony** [comment]
Hmm, it's working fine for the registry so I suspect a silly mistake in our node code. I'll have a look.

**Comment by billt-hlit** [comment]
Sorry, my node wasn't showing up at all because I had it configured for unicast, so I was seeing someone else's. With everything configured correctly, the mDNS advertisements are coming across correctly.

**Comment by garethsb-sony** [comment]
Thanks, Bill, that's good news.

FWIW, there are discussions that could be had about (a) whether to also advertise/browse via mDNS when in unicast DNS-SD mode, (b) whether to attempt to use DNS Update to try to advertise when in unicast DNS-SD mode. The conversations I've had so far suggest deployments will use solely either one or the other, are unlikely to allow DNS Update, and no-one is browsing for Node APIs anyway.
