### ISSUE TITLE
Feature request: Handle Node <-> Registry error conditions

### ISSUE THREAD

**Issue by TSPMP** [sony/nmos-cpp#5]
The current implementation does not handle the error conditions as described in https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2/docs/4.1.%20Behaviour%20-%20Registration.md

The example Node API implementation rather discovers a registration server via mDNS/DNS-SD and expects it to be alive indefinitely. Any errors are logged but not handled.

**Comment by garethsb-sony** [comment]
Thanks. This is our next hole to fill, so I think we'll be working on this during the next couple of weeks.

**Comment by garethsb-sony** [comment]
@TSPMP The new functionality seems to be working well in initial tests here so I've pushed to this repo. However, there's a good deal of asynchronicity in this node behaviour (with respect to both internal changes to the node resources and external network/registry behaviour), so any additional testing you do would be much appreciated!

**Comment by garethsb-sony** [comment]
The behaviour as now implemented, based on the specification, is summarised by the following diagram:

![NMOS Node Behaviour](https://user-images.githubusercontent.com/31761158/38996233-b4a46400-43e2-11e8-9bdf-3b6e8f08663e.png)
Copyright (c) 2017 Sony Corporation. All Rights Reserved.

**Comment by garethsb-sony** [comment]
After a month of further testing this seems to be working well. Expiry based on TTL of cached Registration APIs isn't implemented but otherwise it is per spec.
