### ISSUE TITLE
nmos-cpp-registry does not handle host_addresses or host_address options/settings as indicated in comments of main.cpp

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#50]
The comments in nmos-cpp-registry/main.cpp around line 78 indicate that if the host_addresses setting was omitted, then add all the interface_addresses. The actual code does not check to see if the host_addresses is in the settings. Instead, it just unconditionally uses all the interface_addresses.

Similarly for host_address except that the actual code checks to see if host_addresses is present instead of checking to see if host_address is not present.

The effect is that adding the host_address or host_addresses settings to the command line does not really do what you were wishing for.

The current code looks like:

        // if the "host_addresses" setting was omitted, add all the interface addresses
        const auto interface_addresses = web::http::experimental::interface_addresses();
        if (!interface_addresses.empty())
        {
            web::json::insert(registry_model.settings, std::make_pair(nmos::fields::host_addresses, web::json::value_from_elements(interface_addresses)));
        }

        // if the "host_address" setting was omitted, use the first of the "host_addresses"
        if (registry_model.settings.has_field(nmos::fields::host_addresses))
        {
            web::json::insert(registry_model.settings, std::make_pair(nmos::fields::host_address, nmos::fields::host_addresses(registry_model.settings)[0]));
        }

And should probably look like:

        // if the "host_addresses" setting was omitted, add all the interface addresses
        if (registry_model.settings.has_field(nmos::fields::host_addresses) == false)
        {
            const auto interface_addresses = web::http::experimental::interface_addresses();
            if (!interface_addresses.empty())
            {
                web::json::insert(registry_model.settings, std::make_pair(nmos::fields::host_addresses, web::json::value_from_elements(interface_addresses)));
            }
        }

        // if the "host_address" setting was omitted, use the first of the "host_addresses"
        if (registry_model.settings.has_field(nmos::fields::host_address) == false)
        {
            web::json::insert(registry_model.settings, std::make_pair(nmos::fields::host_address, nmos::fields::host_addresses(registry_model.settings)[0]));
        }

**Comment by garethsb-sony** [comment]
Have you tested this? I think the current code should work correctly, because ``web::json::insert`` follows the ``std::map`` school of insert, i.e. that it doesn't insert if the key is already present.

**Comment by jwpwh** [comment]
I went back and tried it again and you are right that it works ok. The comments seem a little misleading but it does seem to work ok. I was having an issue where my machine has 2 interfaces and I wanted to force it to just one interface. I needed to set host_addresses as well as host_name since the ip address I did not want was the ip address associated with the host name.

**Comment by flingwithwind** [comment]
> I needed to set host_addresses as well as host_name since the ip address I did not want was the ip address associated with the host name.
I have the same problem, and I handle it like this:(a little urgly)
`interface_addresses.resize(1);`

**Comment by garethsb-sony** [comment]
Sorry, I don't understand your comment. By specifying all three properties you should have full control without any code change.

```json
{
  "host_name": "my.example.com",
  "host_addresses": ["192.0.2.42", "198.51.100.42", "203.0.113.42"],
  "host_address": "203.0.113.42"
}
```

Please let me know if something doesn't work for you.
