### ISSUE TITLE
Value of sender_id in staged parameters of receiver after processing an SDP, should it be null?

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#51]
In https://raw.githubusercontent.com/AMWA-TV/nmos-device-connection-management/v1.0.x/APIs/schemas/v1.0-receiver-stage-schema.json the description for sender_id indicates that the sender_id should be null if the receiver has not been configured to receive anything or if it is receiving from a non-NMOS sender. 

Does this mean that when using the nmos-explorer to paste an SDP into a receiver, it should be assumed that the SDP is for a non-NMOS sender and that the sender_id should be set to null? (Maybe somewhere in handle_connection_resource_patch() in nmos/connection_api.cpp)

**Comment by garethsb-sony** [comment]
Good question. My understanding is *no*. Staging a transport file is only an alternative to staging transport parameters, it should not affect other parts, such as the sender id or master enable flag. If a client wants to guarantee sender id is cleared, they should also pass sender id of ``null`` in the same request. Potentially worth asking this question on the AMWA-TV/nmos-device-connection-management repo issue tracker though.

**Comment by jwpwh** [comment]
Andrew Bonney responded to https://github.com/AMWA-TV/nmos-device-connection-management/issues/59 and you are exactly right. It is the responsibility of the client to set all the relevant information and the server should not make any assumptions.

Closing this issue since it seems that further discussion is not needed.

Thanks.
