### ISSUE TITLE
Access to current registration service in use

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#54]
In JT-NM TR-1001, section 10.2.6, it indicates:

> Media Nodes should, through product-specific means, provide a status parameter indicating which registration service is currently in use.

The registration service in use is reported from the node_behaviour_thread. Is there a way outside of this thread to get the registration service currently in use? If so, what is it? If not, should there be?

**Comment by garethsb-sony** [comment]
I originally had the discovered registries list in settings, but never needed it outside of node_behaviour_thread, so I made it local. But if TR-1001 says so, we can put it back. :-)

**Comment by billt-hlit** [comment]
@jwpwh: Sounds like a job for IS-07.  :smile:

Regarding setting the DNS-SD domain, that's sort of what lead me to submit #52 -- I expect that, to fully support having DNS-SD configurable for unicast, automatic domain detection, or manual domain detection, it would probably be best to have the domain settable on the fly -- and I'd really not have arbitrary machines on the network setting the domain for us. So, I figure I'll restrict the settings port to 127.0.0.1.

**Comment by garethsb-sony** [comment]
@jwpwh The discovered registration services (of which the first one is currently in use) are now available in the settings json object (and thus exposed via the Settings API if not disabled).

@billt-hlit I'm not ignoring #52, but more precise control of interface/address per API will probably come as part of a larger effort to add support for running behind a reverse proxy.

**Comment by jwpwh** [comment]
I have tried the new changes and see int registration services listed. This is the information I was expecting. 

Is there any kind of notification when the registry changes? My application has a hook from the implementation thread but this only gets called on activation type events which don't seem related to a change in the registry.

Thanks.

**Comment by garethsb-sony** [comment]
There's no specific notification callback, but updates to the settings are covered by the same model lock, so you can use a thread that waits on the model mutex with an appropriate condition - which could be the implementation thread.

**Comment by jwpwh** [comment]
This looks fine. I am going to close this issue.
