### ISSUE TITLE
node takes exception when registry exits 

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#55]
Scenario:

* On windows 10, C++ REST SDK built with asio
* Start registry on a different system. Happens to be a linux box running the registry. The registry is from sony/nmos-cpp.
* Start nmos-cpp-node on the Windows system. (not as administrator)
* Node comes up, registers the sample node, device, etc.. All is good
* Go to linux box and kill the registry
* The nmos-cpp-node running on the Windows system will exit. In the debugger, it takes an exception. The first non-system code is in cpprestsdk/install/include/cpprest/streams.h line 1094 and it looks like m_helper is empty so it is throwing an exception due to an uninitialized stream object. Call Stack attached below.
* There are also two other instances of nmos-cpp-node running on a different linux system and these nodes do not crash. They are a little older and were not built with asio.

I have seen other issues talking about changes to cpprestsdk and I am not running with all the latest commits so it is possible that what I am seeing is already addressed. It did not seem like these other issues were seeing crashes when the registry terminated so it also seems possible that this is a new issue. 

Has anyone else seen this? Thanks.

Call stack from the crash

[CallStackExceptionWhenRegistryExits.txt](https://github.com/sony/nmos-cpp/files/2841321/CallStackExceptionWhenRegistryExits.txt)

**Comment by garethsb-sony** [comment]
Yes, this is resolved as of cpprestsdk 2.10.9.

**Comment by jwpwh** [comment]
Great! Just what I was hoping to hear. Thanks

**Comment by garethsb-sony** [comment]
Yes, I was rather glad too! When you've tested, please let me know so we can close this, and also #54 if you have a chance.

**Comment by jwpwh** [comment]
Verified that with cpprestsdk 2.10.9 the exception does not happen.
