### ISSUE TITLE
registry with 1.3, subscriptions query is empty

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#56]
With the registry that supports 1.3-dev, doing a query in a browser (e.g. chrome) like http://192.168.87.26:3211/x-nmos/query/v1.3/subscriptions returns []. (i.e. no subscriptions are found). If the v1.3 is changed to v1.2, then 5 subscriptions are returned.

Given that the 1.3 is still under development, is this to be expected?

I ask because I think the Fox Dirty Hands workshop is planning to use the newest sony registry. It seems like if there is an app doing 1.3 queries, then it might not be happy.

**Comment by garethsb-sony** [comment]
Subscriptions are only returned for the current API version. This is per the spec though I can't immediately find the words that make that clear.

**Comment by garethsb-sony** [comment]
Ah, link from nmos-cpp source code: https://basecamp.com/1791706/projects/10192586/messages/70664054#comment_544216653
@andrewbonney, do you think we ought to clarify this in the spec itself?

**Comment by andrewbonney** [comment]
Yes, if it's not explicit it should be. I note as a result I've made an error in https://github.com/AMWA-TV/nmos-discovery-registration/pull/83/files as subscriptions shouldn't be translated.

I'll update that PR with a clarification.

**Comment by jwpwh** [comment]
I had the wrong expectation as to what was being returned on the query that I was making. I was doing a GET so it was returning what subscriptions actually existed with current clients. Given that the only query client being run was the Riedel nmos-explorer, all the subscriptions were v1.2. When I stopped the nmos-explorer, the subscriptions disappeared. 

Is the discussion about non-translation of subscriptions due to the difference between objects registered  by clients (i.e. nodes, devices, flows, senders, sources, and receivers) and a subscription which is a communications device between the query client and the query API server? Is it correct to assume that a v1.3 query api client can learn about v1.2 objects through a v1.3 subscription?

**Comment by garethsb-sony** [comment]
> Is it correct to assume that a v1.3 query api client can learn about v1.2 objects through a v1.3 subscription?

Given a registry that supports both v1.2 and v1.3,

* A v1.3 client can learn about v1.2 resources, provided that the registry supports the "downgrade" trait, which our registry does. Simply include ``"query.downgrade": "v1.2"`` in the ``"params"`` object.

* A v1.2 client *will* learn about v1.3 objects, because all registries are required to downgrade ('strip') higher minor versioned resources.
