### ISSUE TITLE
Setting Staged parameters with an SDP with no source-filter does not set multicast address

### ISSUE THREAD

**Issue by jwpwh** [sony/nmos-cpp#57]
The attached file is an sdp without a source-filter attribute

[sdp_with_no_source_filter.txt](https://github.com/sony/nmos-cpp/files/2885215/sdp_with_no_source_filter.txt)

When this sdp is pasted into the staged parameters (using nmos-explorer) the multicast address is not set.

There are comments in nmos/sdp_utils.cpp which might lead one to believe that the multicast address is supposed to be set, but the code is different from the comments.

The line in question is line 652

`
// media connection data overrides session connection data (if no source filter)
if (params[nmos::fields::source_ip].is_null())
`

The comment says "if no source filter", which is the case for this SDP. But the code says no source_ip which is almost certainly set because of line 589

`params[nmos::fields::source_ip] = value::string(sdp::fields::unicast_address(sdp::fields::origin(session_description)));`

I think source-filters are highly desired, maybe even considered required, but it is also apparent that not all vendors are supplying them, at least not yet. If no source-filter is present, is it intended to get a multicast-ip like the comments indicate?

**Comment by simonlo-sony** [comment]
Thank you for your report, we have found the solution, will push the fix in shortly.

**Comment by garethsb-sony** [comment]
@jwpwh Please would you mind reviewing c1ff111fa13db2cb36892f0123ea5873731076bb before I merge to master? Thanks!

**Comment by jwpwh** [comment]
I looked over the changes and they look good to me.  As a review, the session connection data is applied first, then the media connection data and finally the source-filter information, if present.

I also applied the changes and tried the code with the example I had provided before. Now, instead of a null multicast_ip, the field is properly assigned.

Thanks.

**Comment by garethsb-sony** [comment]
Thanks.
