### ISSUE TITLE
Errors while registering advertisement

### ISSUE THREAD

**Issue by thosil** [sony/nmos-cpp#60]
Hello,
I'm trying to build a container for the nmos-cpp-registry and I'm facing problems while advertising the services.
They could not be found using avahi-browse and I see the following lines in the stdout:
```
...
2019-02-25 14:13:16.613: error: 140539986867968: DNSServiceRegister reported error: -65563 while registering advertisement for: nmos-cpp_query_10-129-4-108:3211._nmos-query._tcp
2019-02-25 14:13:19.614: error: 140539978475264: DNSServiceRegister reported error: -65563 while registering advertisement for: nmos-cpp_registration_10-129-4-108:3210._nmos-registration._tcp
2019-02-25 14:13:22.616: error: 140539970082560: DNSServiceRegister reported error: -65563 while registering advertisement for: nmos-cpp_registration_10-129-4-108:3210._nmos-register._tcp
2019-02-25 14:13:25.617: error: 140539961689856: DNSServiceRegister reported error: -65563 while registering advertisement for: nmos-cpp_node_10-129-4-108:3212._nmos-node._tcp
...
```

I'm running the container with these options:
```
docker run -P --network host --name NMOS-REGISTRY sony-nmos-registry
```

The image itself (derived from an Ubuntu 18.10) is built using these packages:

From Ubuntu repositories:
- libboost-chrono1.67.0
- libboost-date-time1.67.0
- libboost-regex1.67.0
- libboost-system1.67.0
- libboost-thread1.67.0
- libboost-atomic1.67.0
- libboost-filesystem1.67.0
- libboost-random1.67.0
- libboost-serialization1.67.0

From source:
- github microsoft/cpprestsdk v2.10.8
- Apple mDNSResponder 878.30.4
- your patch "poll-rather-than-select.patch"
- and this repo (branch master)

I really don't know where to look at to find a way to make it working as expected, the same procedure *outside* a container is working like a charm.

I can publish the Dockerfile if needed.

Do you have any advise?

**Comment by garethsb-sony** [comment]
Hi Thomas.

-65563 is the dns_sd.h error code ``kDNSServiceErr_ServiceNotRunning`` so I think it's likely you just need to start the ``mdnsd`` daemon in the container before launching ``nmos-cpp-registry``, and it will start working.

However, you may also be interested to know that Richard Hastie, @rhastie, has a working Dockerised Registry which is using Avahi rather than mDNSResponder.

**Comment by billt-hlit** [comment]
+1 on the documentation. A point on the trade-offs: mdnsd exits promptly, with a message hidden on stderr rather than logged, on a Linux system (and probably others) that doesn't have IPv6 in the kernel. I'm working on a patch, but may simply have to build it with v6 disabled. A little gotcha, but it's still a gotcha.

**Comment by garethsb-sony** [comment]
On the other hand, who reads documentation? The point about needing to disable IPv6 (and how to do so) is covered in the [DNS Service Discovery](https://github.com/sony/nmos-cpp/blob/master/Documents/Dependencies.md#dns-service-discovery) section of the docs.

**Comment by billt-hlit** [comment]
Urgh, how embarrassing....

**Comment by garethsb-sony** [comment]
No - honestly, it's a salient reminder that no-one, not even those we *know* are paying attention, will read/remember all the documentation. :-/

**Comment by thosil** [comment]
To be honest, I read most of the documentation, but not the "Tutorial - Preparation" where it's very clear, I'm sorry :confused:

But I wanted to thank you because now it's working using the mdnsd in the container, my image is weighting only 165MB which is handy for offline installation/upgrade.

Of course I found the mellanox/nmos-cpp-avahi after doing my own image...

I'm interested to know the main differences between Avahi and mDNSResponder.

**Comment by garethsb-sony** [comment]
Thanks, Thomas, that's great news. I will try to update the docs here on Avahi vs mDNSResponder, or add something at https://github.com/AMWA-TV/nmos/wiki

**Comment by gl0522** [comment]
> The double dot at the end of the names it's trying to register suggests that it has failed to identify a domain. Try modifying the config file with `"domain": "local"` and see if that helps.

Thank you very much for your suggestion

The command used for the above error is docker run it -- net=host -- rm rhastie/nmos cpp: latest

However, when using the **docker run it -- net=domain -- rm rhastie/nmos cpp: latest command,** the error message is as follows
docker: Error response from daemon: network domain not found.

when using the **docker run it -- net=local -- rm rhastie/nmos cpp: latest command,** the error message is as follows
docker: Error response from local : network local not found.

the docker network as follows

NETWORK ID     NAME      DRIVER    SCOPE
89eb8ecc6a6a   bridge    bridge    local
6443dd0f5d1c   host      host      local
24558bb6e174   none      null      local

However, using the docker run it -- net=host -- rm rhastie/nmos cpp: latest command to rerun on Ubuntu 18.04 system did not result in any errors

Is the startup of the rhastie/nmos cpp container related to the server system version? Or is it related to the Docker version?
