### ISSUE TITLE
nmos-cpp-node accepts IS-05 PATCH request with "" transport_file results in 200 SUCCESS

### ISSUE THREAD

**Issue by billt-hlit** [sony/nmos-cpp#63]
I ran into this strange edge case: I had to chase down a bug in my code because empty transport_file data injected by my code was causing exceptions in the JSON parser. When I use empty data via the API, on the other hand, nmos-cpp-node thinks everything's fine, going so far as to report back the zero-length SDP:

The request:
> curl -H 'Content-Type: application/json' -H 'Accept: application/json' -X PATCH http://d13:3215/x-nmos/connection/v1.0/single/receivers/1e6ee63a-3d30-5788-b0c2-07e97d77e375/staged -d '{"activation":{"mode":"activate_immediate"},"master_enable":true, "sender_id":"855c19a5-5ee8-5c7b-86b3-6d1f4b7f70d8","transport_file":{"data": "", "type":"application/sdp"}}'

The response;
> {"activation":{"activation_time":"1551397926:995761753","mode":"activate_immediate","requested_time":null},"master_enable":true,"sender_id":"855c19a5-5ee8-5c7b-86b3-6d1f4b7f70d8","transport_file":{"data":"","type":"application/sdp"},"transport_params":[{"destination_port":"auto","interface_ip":"auto","multicast_ip":null,"rtp_enabled":true,"source_ip":null},{"destination_port":"auto","interface_ip":"auto","multicast_ip":null,"rtp_enabled":true,"source_ip":null}]}

**Comment by billt-hlit** [comment]
OK, so this behavior looks to be deliberate in connection_api.cpp:
```
if (!transport_file.is_null() && !transport_file.as_object().empty())
```
Looking at ConnectionAPI.raml, I see that the is_null() part is required, but it isn't obvious from the spec that an empty string should receive special treatment. Not obvious it shouldn't, either....

**Comment by garethsb-sony** [comment]
Yes, I suspect that's a flaw. Empty string should get rejected, but gets treated the same as ``null`` (which is valid).

**Comment by garethsb-sony** [comment]
FWIW, the ``as_object().empty()`` check is for empty json object for the top-level ``"transport_file"`` attribute, not the inner ``"data"`` being an empty string. That is due to the ``get_transport_type_data`` function and the code two lines later:

```C++
if (!transport_type_data.second.empty())
```

**Comment by billt-hlit** [comment]
Looks good. Thanks, Gareth!

**Comment by garethsb-sony** [comment]
Sorry, @billt-hlit, I missed a related case of a mistakenly accepted PATCH with

```json
{
  "transport_file": {
    "data": "foobar",
    "type": ""
  }
}
```

Now fixed.
