### ISSUE TITLE
prevent nmos-cpp-registry to create a node

### ISSUE THREAD

**Issue by thosil** [sony/nmos-cpp#64]
Hi,

when the nmos-cpp-registry starts, it also instantiate an NMOS IS-04 Node.
Is there a way (a flag) to prevent it and just start the query and registration services?

Thanks

**Comment by simonlo-sony** [comment]
Hi,

At the moment setting -1 for node_port will only prevent it advertising itself as _nmos-node._tcp, but not excluding itself from the query.  We will review your request, for the time being you could set node_port to -1 and insert the node_port test around the "Configure the Node API" in nmos-cpp-registry's main.cpp for the temporary solution.

```
if(-1 < nmos::fields::node_port(registry_model.settings))
{
        // Configure the Node API
        port_routers[{ {}, nmos::fields::node_port(registry_model.settings) }].mount({}, nmos::make_node_api(registry_model, {}, gate));

        // set up the node resources
        auto& self_resources = registry_model.node_resources;
        nmos::experimental::insert_registry_resources(self_resources, registry_model.settings);

        // add the self resources to the Registration API resources
        // (for now just copy them directly, since these resources currently do not change and are configured to never expire)
        registry_model.registry_resources.insert(self_resources.begin(), self_resources.end());
}
```
Best regards,
Simon

**Comment by garethsb-sony** [comment]
Out of interest, @thosil, why do you want this?

**Comment by thosil** [comment]
Well, in fact I especially wonder why nmos-cpp-registry exposes a NMOS node :sweat_smile: 
If I want an NMOS node I'll start one aside, either a real one or a mock loaded with resources, but having an empty node seems to me a little bit useless, but maybe I'm missing the point.

**Comment by garethsb-sony** [comment]
Originally the NMOS introductory documentation talked about everything on the network should be a node, so that's what we did. I think the situation is a bit more nuanced now. However it also has one real purpose /advantage, in that it gives the registry somewhere to advertise the other services that it supports in a standard way, in the "services" of its node resource.

**Comment by thosil** [comment]
ok, I get the idea now ;-)
Thanks!

**Comment by garethsb-sony** [comment]
On balance, therefore, I'm going to close this, since the node resource exposed by nmos-cpp-registry does serve a small but useful purpose.
