### ISSUE TITLE
v1.2 senders with null flow_id not accepted by nmos-cpp-registry

### ISSUE THREAD

**Issue by thosil** [sony/nmos-cpp#66]
The spec for v1.1 senders and upper allows senders to have flow_id = "null" but the nmos-cpp-registry does not like it, refusing to register the sender with a little warning in the logs: "JSON error: not a string".
Of course if one register a sender with flow_id null, how could it be rendered in v1.0?
Also, we need to provide a manifest file, and we certainly have enough information to create a flow.  
So maybe it's not really an issue with nmos-cpp but rather with the spec?

**Comment by garethsb-sony** [comment]
> The spec for v1.1 senders and upper allows senders to have flow_id = "null" but the nmos-cpp-registry does not like it, refusing to register the sender with a little warning in the logs: "JSON error: not a string".

That's absolutely a bug. Will fix and add to the nmos-testing test suite. Thanks for the report.

> Of course if one register a sender with flow_id null, how could it be rendered in v1.0?

That's an open issue that we're already discussing in the spec and in the test suite.

**Comment by garethsb-sony** [comment]
Spec: https://github.com/AMWA-TV/nmos-discovery-registration/issues/67

Testing: https://github.com/AMWA-TV/nmos-testing/issues/114

**Comment by garethsb-sony** [comment]
Fixed in https://github.com/sony/nmos-cpp/commit/d6161defbf164f71b2d0b3c07791d89e97760d40

Test case added in https://github.com/AMWA-TV/nmos-testing/pull/165

Thanks again for the report, @thosil.
