### ISSUE TITLE
Distinguish mdns advertisements for registration and register

### ISSUE THREAD

**Issue by prince-chrismc** [sony/nmos-cpp#67]
I ran into a small issue debug some of my components tests over mdns. I was not able to tell the v1.2 advertisement from the v1.3 advertisement since they both included the same "instance_name". 

I had to modify the following to have different advertisements.

https://github.com/sony/nmos-cpp/blob/0c94436c4dc95a49fb0dbd8b7a02f1f8b9bd16aa/Development/nmos/mdns.cpp#L204

Should this not return `"register"`

https://github.com/sony/nmos-cpp/blob/0c94436c4dc95a49fb0dbd8b7a02f1f8b9bd16aa/Development/nmos/mdns.cpp#L261

```
advertiser.register_service( service_name( nmos::service_types::register_, settings ), nmos::service_types::register_, instance_port, domain, host_name, txt_records).wait();
```

Is there a particular reason for the current behavior?

**Comment by garethsb-sony** [comment]
The same service (i.e. Registration API) instance, with the same txt records (pri, api_ver, api_proto), is being advertised via two different service types. I don't understand why you would want the instance information to be different.

**Comment by prince-chrismc** [comment]
Simply so that the different service advertisements can easily be distinguished by the name.

I had not come up with they are the same instance so they should be named the same. I just wanted to understand the reasoning behind the current implementation. Thank you for the insight.

**Comment by garethsb-sony** [comment]
If it's necessary to distinguish between them for debugging purposes (on the Node side?) is it possible to just use the service type itself?

**Comment by prince-chrismc** [comment]
Of course that would be possible, however it was faster to modify the server to have different entries. The component test simply were not imagined with that complexity.

**Comment by garethsb-sony** [comment]
OK. Thanks. I can't see a good reason for any change at the moment, so I'll close for now.
