### ISSUE TITLE
Compilation completed, but fails nmos-cpp-registry-test

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-cpp#7]
Please bear in mind I'm installing this into a docker conatiner with a base of Ubuntu 16.04. Compilation is now complete but after running nmos-cpp-registry-test from build directory I get alerted to failed tests. All packages are installed into /home.  Looks related to MDNS. I have installed "mDNSResponder-878.30.4" and ran the following:

> cd /home/mDNSResponder*/mDNSPosix
> set HAVE_IPV6=0
> make os=linux
> make os=linux install

Packages installed to get compilation to work are: 

> RUN apt-get update && apt-get install -y --no-install-recommends \
>     g++ build-essential openssl libssl-dev && rm -rf /var/lib/apt/lists/*

Output from nmos-cpp-registry-test:

> root@ubuntu:/home/nmos-cpp/Development/build# ./nmos-cpp-registry-test 
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> nmos-cpp-registry-test is a Catch v1.10.0 host application.
> Run with -? for options
> 
> -------------------------------------------------------------------------------
> testMdnsAdvertiseAPIs
> -------------------------------------------------------------------------------
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:91
> ...............................................................................
> 
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:117: FAILED:
>   CATCH_REQUIRE( gate.hasLogMessage("Advertisement started for 3 service(s)") )
> with expansion:
>   false
> 
> -------------------------------------------------------------------------------
> testMdnsBrowseAPIs
> -------------------------------------------------------------------------------
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:127
> ...............................................................................
> 
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:153: FAILED:
>   CATCH_REQUIRE( gate.hasLogMessage("Advertisement started for 3 service(s)") )
> with expansion:
>   false
> 
> -------------------------------------------------------------------------------
> testMdnsResolveAPIs
> -------------------------------------------------------------------------------
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:199
> ...............................................................................
> 
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:228: FAILED:
>   CATCH_REQUIRE( gate.hasLogMessage("Advertisement started for 1 service(s)") )
> with expansion:
>   false
> 
> ===============================================================================
> test cases:  29 |  26 passed | 3 failed
> assertions: 225 | 222 passed | 3 failed
> 
> root@ubuntu:/home/nmos-cpp/Development/build#

Finally I've pushed the Dockerfile/Makefile to my Github if you'd like to take a look: [https://github.com/rhastie/docker-nmos-cpp](https://github.com/rhastie/docker-nmos-cpp). The Dockerfile should show you the build process I'm trying to automate.

Any help appreciated
Thanks,

**Comment by garethsb-sony** [comment]
Have you started ``mdnsd``? Sorry if that's a silly question!

**Comment by rhastie** [comment]
Getting there :)... Ok - it's been a long day with this... Some school boy errors creeping in. Lol.

Just ran "service mdns start" and output:

> Starting Apple Darwin Multicast DNS / DNS Service Discovery daemon: mdnsd.
> root@ubuntu:/home# mDNSResponder: mDNSResponder (Engineering Build) (May  1 2018 13:47:43) starting
> mDNSResponder: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy (0)

Re-ran tests, getting better. It nows looks like its the container IP addressing causing problems. Output is:

> root@ubuntu:/home/nmos-cpp/Development/build# ./nmos-cpp-registry-test 
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> nmos-cpp-registry-test is a Catch v1.10.0 host application.
> Run with -? for options
> 
> -------------------------------------------------------------------------------
> testMdnsResolveAPIs
> -------------------------------------------------------------------------------
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:199
> ...............................................................................
> 
> /home/nmos-cpp/Development/mdns/test/mdns_test.cpp:257: FAILED:
>   CATCH_REQUIRE( resolved.ip_address == ipAddress )
> with expansion:
>   "192.168.6.103" == "127.0.1.1"
> 
> ===============================================================================
> test cases:  29 |  28 passed | 1 failed
> assertions: 241 | 240 passed | 1 failed

IP address 192.168.6.103 is my host. Output from ifconfig inside the container:

> root@ubuntu:/home/nmos-cpp/Development/build# ifconfig
> docker0   Link encap:Ethernet  HWaddr 02:42:3b:c6:f8:27
>           inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
>           inet6 addr: fe80::42:3bff:fec6:f827/64 Scope:Link
>           UP BROADCAST MULTICAST  MTU:1500  Metric:1
>           RX packets:152914 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:269497 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0
>           RX bytes:8655712 (8.6 MB)  TX bytes:430112486 (430.1 MB)
> 
> ens33     Link encap:Ethernet  HWaddr 00:0c:29:50:b4:ca
>           inet addr:192.168.6.103  Bcast:192.168.6.255  Mask:255.255.255.0
>           inet6 addr: fe80::bb5b:d3eb:be0c:b112/64 Scope:Link
>           UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
>           RX packets:525946 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:369602 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:660601764 (660.6 MB)  TX bytes:149540429 (149.5 MB)
> 
> lo        Link encap:Local Loopback
>           inet addr:127.0.0.1  Mask:255.0.0.0
>           inet6 addr: ::1/128 Scope:Host
>           UP LOOPBACK RUNNING  MTU:65536  Metric:1
>           RX packets:1013 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:1013 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:1000
>           RX bytes:87352 (87.3 KB)  TX bytes:87352 (87.3 KB)

Thanks,
Rich.

**Comment by garethsb-sony** [comment]
> It nows looks like its the container IP addressing causing problems.

I concur. I'll have a look at this - our situation inside mininet virtual hosts should be similar.

> Ok - it's been a long day with this... 

Thanks for persevering. Any feedback on specific parts of the docs/README would be much appreciated.

**Comment by rhastie** [comment]
Perseverance isn't a problem - I really like the look of this NMOS Registry implementation. I would welcome a chance to have a conversation. I've LinkedIn to you I believe so if you could swap emails and we can set a call that would be hugely appreciated. I'd like to run you through my thoughts about the switch implementation to get your feedback.

Many Thanks,

**Comment by garethsb-sony** [comment]
> > It nows looks like its the container IP addressing causing problems.
>
> I concur. I'll have a look at this - our situation inside mininet virtual hosts should be similar.

I've reproduced this - we need to re-evaluate how we determine the host's IP addresses in the test code.

**Comment by garethsb-sony** [comment]
@rhastie, a few questions if you don't mind:

Within your container what does ``hostname`` report?
What's in its _/etc/hosts_ file?
What does ``host <hostname>.`` report?

Thanks!

**Comment by garethsb-sony** [comment]
@rhastie, thankyou. Right then, that's all as I (now) expected. Please would you mind confirming the output of:

- ``hostname --fqdn``
- ``hostname --ip-address``
- ``hostname --all-ip-addresses``

Thanks!

**Comment by rhastie** [comment]
Here you go… :)

root@ubuntu:/# hostname --fqdn
ubuntu
root@ubuntu:/# hostname --ip-address
127.0.1.1
root@ubuntu:/# hostname --all-ip-addresses
192.168.6.103 172.17.0.1
root@ubuntu:/#

Thanks!

**Comment by garethsb-sony** [comment]
We have updated the registry and node implementations to set their node resource’s api.endpoints based on the interfaces found at start up.
To override this, specify the new “host_addresses” setting on the nmos-cpp-registry/-node command line.

If the (existing) “host_address” setting is specified, it is used in the NMOS data model wherever only a single address is allowed, as before.
If it is left unspecified, the first of the “host_addresses” is used.*

Note: do not specify “0.0.0.0” for the “host_address”; node and registry always listen on all interfaces no matter what.

Possible future work:

-	Use default route information or metrics to determine the primary “host_address” automatically (*rather than essentially picking one at random, due to unreliable ordering from getifaddrs)
-	Dynamically update the “host_addresses” by polling the interfaces intermittently, and update the data model accordingly

Please let me know when you can if this works for you.

**Comment by rhastie** [comment]
Closed - Gareth thanks for the assistance
