### ISSUE TITLE
Question - Rejecting IS-05 resource updates

### ISSUE THREAD

**Issue by wsneijers** [sony/nmos-cpp#78]
In the provide node example there is an example node implementation (`node_implementation.cpp`). In that implementation there is a infinite for loop which waits for resource updates from the connection API. When detected it updates the corresponding node and connection resource. 

Is it possible to reject an update from this point and return an error code instead from the API? I Know there are the constraints, but according to the documentation it should also be possible to return a 500 error code. For example we have a situation where a separate program can decide to reject an update to it's senders and receivers if the format is not supported (which you cannot constrain as far as I can see).

**Comment by garethsb-sony** [comment]
Yes, I think we need that, especially for rejecting `/staged` requests due to information in SDP that doesn't have corresponding transport parameters. We started thinking about that here: https://github.com/sony/nmos-cpp/issues/76#issuecomment-497423916.

We're focused on the AMWA NMOS API Security virtual workshop going on this week, but I'll try to look at this asap.

**Comment by wsneijers** [comment]
Good to know, thanks for the quick response!

**Comment by garethsb-sony** [comment]
@wsneijers I updated #76 with some more thoughts.

**Comment by garethsb-sony** [comment]
I think this will be dealt with via the new `transport_file_parser` parameter on `nmos::make_connection_api`. It is a function like:

`web::json::value parse_rtp_transport_file(const nmos::resource& receiver, const nmos::resource& connection_receiver, const utility::string_t& transport_file_type, const utility::string_t& transport_file_data, slog::base_gate& gate);`
  * [in] `receiver` - IS-04 receiver
  * [in] `connection_receiver` - IS-05 receiver
  * [in] `transport_file_type` - base media type, e.g. "application/sdp"
  * [in] `transport_file_data` - contents of the file
  * [in out] `gate` - logging gateway
  * [result] `transport_params` - array of transport params, must be the correct size!
  * [throw] `std::runtime_error` - will be mapped to 500 Internal Error (as required for transport file errors by the spec) 

The default implementation will be the same as now, see https://github.com/sony/nmos-cpp/pull/81/files#diff-174ea772e8841e5e094fe9f2d834af0fR878, but it could be replaced with one that did additional validation of the SDP file.

**Comment by garethsb-sony** [comment]
Closed by #81.
