### ISSUE TITLE
websocket++ library required, contrary to dependencies.md

### ISSUE THREAD

**Issue by billt-hlit** [sony/nmos-cpp#8]
Hi, Gareth,

According to Dependencies.md, "A copy of the header-only WebSocket++ v0.5.1 is included in the C++ REST SDK, so a separate installation is not necessary." However, the nmos-cpp CMakeLists.txt searches for a websocketpp-config.cmake, so cmake fails if the development library is not present. For example, on my 32-bit Ubuntu 16.04 system, I see:

```
: [xenial32]bt@hobbes:git/nmos-cpp/Development/build; sudo apt remove libwebsocketpp-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libwebsocketpp-dev' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
: [xenial32]bt@hobbes:git/nmos-cpp/Development/build; /home/bt/.local/bin/cmake  ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.8") 
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Found cpprestsdk
CMake Error at CMakeLists.txt:44 (find_package):
  By not providing "Findwebsocketpp.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "websocketpp", but CMake did not find one.

  Could not find a package configuration file provided by "websocketpp"
  (requested version 0.5.1) with any of the following names:

    websocketppConfig.cmake
    websocketpp-config.cmake

  Add the installation prefix of "websocketpp" to CMAKE_PREFIX_PATH or set
  "websocketpp_DIR" to a directory containing one of the above files.  If
  "websocketpp" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
```

I'm hoping the cmake files can be fixed, as I rather avoid the websocket++ dependency.

Thanks,
Bill

**Comment by garethsb-sony** [comment]
Hi Bill,

Sorry, this is covered in the [Getting Started](../blob/master/Documents/Getting-Started.md) guide:

> set ``WEBSOCKETPP_INCLUDE_DIR`` (PATH) to the location of the WebSocket++ include files, e.g. ``.../Release/libs/websocketpp`` within the C++ REST SDK source tree

Does that make sense? I'll add that sentence to Dependencies.md as well.

Thanks!

**Comment by billt-hlit** [comment]
I'm still getting errors from cmake despite prefixing the cmake command line with `WEBSOCKETPP_INCLUDE_DIR=../../../cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp/websocketpp`. I also tried that same directory but with an additional "websocketpp".

I am running cmake 3.11, if that has any bearing.

**Comment by garethsb-sony** [comment]
Sorry - it needs to be a CMake variable rather than an environment variable like the example in the Getting Started page.

Like so: ``cmake -DWEBSOCKETPP_INCLUDE_DIR="..." etc.``

**Comment by billt-hlit** [comment]
Duh. Thank you.
