### ISSUE TITLE
Build failure on Debian 9 with boost 1.62

### ISSUE THREAD

**Issue by firthmj** [sony/nmos-cpp#82]
When trying to build the latest version of nmos-cpp with the latest cpprestsdk on Debian 9 (with the system Boost libraries V1.62), I get three errors in client_utils.cpp:

[ 83%] Building CXX object CMakeFiles/nmos-cpp_static.dir/nmos/components.cpp.o
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp: In instantiation of 'nmos::details::make_client_ssl_context_callback(const settings&)::<lambda(boost::asio::ssl::context&)> [with ExceptionType = web::http::http_exception]':
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:32:21:   required from 'struct nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::http::http_exception; nmos::settings = web::json::value]::<lambda(class boost::asio::ssl::context&)>'
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:44:13:   required from 'std::function<void(boost::asio::ssl::context&)> nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::http::http_exception; nmos::settings = web::json::value]'
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:58:118:   required from here
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:42:27: error: invalid user-defined conversion from 'const boost::system::error_code' to 'int' [-fpermissive]
                     throw ExceptionType(e.code(), e.what());
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/asio/io_service.hpp:25:0,
                 from /usr/include/boost/asio/ssl/context.hpp:26,
                 from /home/michael/packages/nmos-cpp/Development/boost/asio/ssl/set_cipher_list.hpp:8,
                 from /home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:4:
/usr/include/boost/system/error_code.hpp:362:7: note: candidate is: boost::system::error_code::operator boost::system::error_code::unspecified_bool_type() const <near match>
       operator unspecified_bool_type() const  BOOST_SYSTEM_NOEXCEPT // true if error
       ^~~~~~~~
/usr/include/boost/system/error_code.hpp:362:7: note:   no known conversion from 'boost::system::error_code::unspecified_bool_type {aka void (*)()}' to 'int'
In file included from /usr/local/include/cpprest/http_client.h:50:0,
                 from /home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:7:
/usr/local/include/cpprest/http_msg.h:222:5: note:   initializing argument 1 of 'web::http::http_exception::http_exception(int, const string_t&)'
     http_exception(int errorCode, const utility::string_t& whatArg)
     ^~~~~~~~~~~~~~
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp: In instantiation of 'nmos::details::make_client_ssl_context_callback(const settings&)::<lambda(boost::asio::ssl::context&)> [with ExceptionType = web::websockets::client::websocket_exception]':
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:32:21:   required from 'struct nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::websockets::client::websocket_exception; nmos::settings = web::json::value]::<lambda(class boost::asio::ssl::context&)>'
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:44:13:   required from 'std::function<void(boost::asio::ssl::context&)> nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::websockets::client::websocket_exception; nmos::settings = web::json::value]'
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:73:137:   required from here
/home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:42:27: error: invalid user-defined conversion from 'const boost::system::error_code' to 'int' [-fpermissive]
                     throw ExceptionType(e.code(), e.what());
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/boost/asio/io_service.hpp:25:0,
                 from /usr/include/boost/asio/ssl/context.hpp:26,
                 from /home/michael/packages/nmos-cpp/Development/boost/asio/ssl/set_cipher_list.hpp:8,
                 from /home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:4:
/usr/include/boost/system/error_code.hpp:362:7: note: candidate is: boost::system::error_code::operator boost::system::error_code::unspecified_bool_type() const <near match>
       operator unspecified_bool_type() const  BOOST_SYSTEM_NOEXCEPT // true if error
       ^~~~~~~~
/usr/include/boost/system/error_code.hpp:362:7: note:   no known conversion from 'boost::system::error_code::unspecified_bool_type {aka void (*)()}' to 'int'
In file included from /home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:8:0:
/usr/local/include/cpprest/ws_client.h:249:5: note:   initializing argument 1 of 'web::websockets::client::websocket_exception::websocket_exception(int, const string_t&)'
     websocket_exception(int errorCode, const utility::string_t& whatArg)
     ^~~~~~~~~~~~~~~~~~~
[ 83%] Building CXX object CMakeFiles/nmos-cpp_static.dir/nmos/connection_activation.cpp.o
[ 84%] Building CXX object CMakeFiles/nmos-cpp_static.dir/nmos/connection_api.cpp.o
CMakeFiles/nmos-cpp_static.dir/build.make:166: recipe for target 'CMakeFiles/nmos-cpp_static.dir/cpprest/ws_listener_impl.cpp.o' failed
make[2]: *** [CMakeFiles/nmos-cpp_static.dir/cpprest/ws_listener_impl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/6/mutex:42:0,
                 from /usr/local/include/pplx/pplxlinux.h:33,
                 from /usr/local/include/pplx/pplx.h:49,
                 from /usr/local/include/pplx/pplxtasks.h:61,
                 from /usr/local/include/cpprest/asyncrt_utils.h:17,
                 from /usr/local/include/cpprest/json.h:18,
                 from /home/michael/packages/nmos-cpp/Development/cpprest/json_ops.h:4,
                 from /home/michael/packages/nmos-cpp/Development/cpprest/json_utils.h:4,
                 from /home/michael/packages/nmos-cpp/Development/nmos/settings.h:4,
                 from /home/michael/packages/nmos-cpp/Development/nmos/client_utils.h:4,
                 from /home/michael/packages/nmos-cpp/Development/nmos/client_utils.cpp:1:
/usr/include/c++/6/functional:2106:7: error: 'std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::http::http_exception; nmos::settings = web::json::value]::<lambda(boost::asio::ssl::context&)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {boost::asio::ssl::context&}]', declared using local type 'nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::http::http_exception; nmos::settings = web::json::value]::<lambda(boost::asio::ssl::context&)>', is used but never defined [-fpermissive]
       function<_Res(_ArgTypes...)>::
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/6/functional:2106:7: error: 'std::function<_Res(_ArgTypes ...)>::function(_Functor) [with _Functor = nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::websockets::client::websocket_exception; nmos::settings = web::json::value]::<lambda(boost::asio::ssl::context&)>; <template-parameter-2-2> = void; <template-parameter-2-3> = void; _Res = void; _ArgTypes = {boost::asio::ssl::context&}]', declared using local type 'nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::websockets::client::websocket_exception; nmos::settings = web::json::value]::<lambda(boost::asio::ssl::context&)>', is used but never defined [-fpermissive]
CMakeFiles/nmos-cpp_static.dir/build.make:218: recipe for target 'CMakeFiles/nmos-cpp_static.dir/nmos/client_utils.cpp.o' failed
make[2]: *** [CMakeFiles/nmos-cpp_static.dir/nmos/client_utils.cpp.o] Error 1
CMakeFiles/Makefile2:261: recipe for target 'CMakeFiles/nmos-cpp_static.dir/all' failed
make[1]: *** [CMakeFiles/nmos-cpp_static.dir/all] Error 2
Makefile:140: recipe for target 'all' failed

It seems to suggest adding'-fpermissive' in the right place may help me, but I'm not 100% sure where the right place would be, or whether there is a better fix.

**Comment by garethsb-sony** [comment]
At a guess, you have too old a version of cpprestsdk, minimum requirement is v2.10.11; specifically I think you're missing this commit https://github.com/microsoft/cpprestsdk/commit/43773b9858f0672a4d5856a48f79d97193b295d9.

**Comment by firthmj** [comment]
I am building with a checkout of the head of trunk for cpprestsdk. I did at one point install a version from the Debian repository, but couldn't even get started with the build, because it was missing all the CMake support files. I'm 99.9% sure I purged the old version before trying again to build nmos-cpp.

As the errors are relating to converting from boost::system::error_code to int, I'm not sure how that commit, which is related to std::error_code, will help.

I managed to get things to compile by adding ".value()" to the end of all similar errors (which in V1.62 of Boost seems necessary to get an integer from an error code), but I'm not sure it will be doing the right thing in all cases.

In particular there was a "chicken and egg" problem trying to fix server_utils.cpp, where one use of "make_listener_ssl_context_callback" was templated with "boost::system::system_error", which failed with the .value() conversion, and one use was templated with "web::websockets::websocket_exception" which failed without it. I bodged it by converting both to use "web::websockets::websocket_exception", which the comment above one says won't work right, but is the intended eventual use.

**Comment by garethsb-sony** [comment]
The error message is misleading - the compiler's looking for a constructor and should pick the ones that take `(std::error_code errorCode, const utility::string_t& whatArg)` but since it didn't match it reported the error based on a different candidate, which has a match if it's allowed to be permissive about `bool` to `int` conversion. The reason the 'right' constructor isn't picked is, I now realise, because Boost 1.62.0 is missing the conversion from `boost::error_code` to `std::error_code` which only arrived in https://github.com/boostorg/system/commit/6010be4144ce126e79a7eee56f5b40eef8085b87 (Boost 1.65.0).

I'll look at a tweak to gain back compatibility with older Boost versions.

**Comment by garethsb-sony** [comment]
> I'll look at a tweak to gain back compatibility with older Boost versions.

There are just a few places in the codebase that rely on the conversion of `boost::system::error_code` to `std::error_code` (e.g. in nmos/client_utils.cpp and nmos/server_utils.cpp), in order to construct 
e.g. `http_exception` or `websocket_exception`.

We need a named function to convert from `boost::system::error_category` to `std::error_category`, which we could just call in those places, and implement as pass-through for Boost 1.65 onwards. We might as well use preprocessor test of `BOOST_VERSION` for that.

I'd imagine such a function to work by returning either a wrapper that's basically `boost::system::error_category::std_category` found in Boost 1.65, or the equivalent `std` category if it's `generic_category` or `system_category`. (Though we can see in the code comments and commit log for Boost.System that comparing error codes/conditions using these categories for equivalence doesn't work perfectly on all platforms/std libs...)

There are a few additional places where we catch either `std::system_error` or `boost:system::system_error` where we should check whether we need to catch both.

**Comment by garethsb-sony** [comment]
To be clear, in the short term, upgrading to Boost 1.65 or higher would solve this issue.
