### ISSUE TITLE
Linux doesn't support the SIGBREAK signal

### ISSUE THREAD

**Issue by duncwebb** [sony/nmos-cpp#93]
Hi there. The change made in /home/ubuntu/nmos-cpp/Development/nmos/process_utils.cpp in commit https://github.com/sony/nmos-cpp/commit/05953292e26c7c0257bf40b98c17d34097c76019 throws a compiler error in Linux as SIGBREAK isn't a standard Posix signal. Does this just need an ifdef around it for Linux builds?

**Comment by garethsb-sony** [comment]
Thanks for the report, and apologies! Yes, I'll do that ASAP.

**Comment by garethsb-sony** [comment]
Fixed by 9d5f358a41694767cc731a3978bfa63dd7a7d27d. Thanks again.

**Comment by duncwebb** [comment]
Fantastic, thanks very much!
