### ISSUE TITLE
‘class web::websockets::client::websocket_client_config’ has no member named ‘set_ssl_context_callback’

### ISSUE THREAD

**Issue by dcrearer** [sony/nmos-cpp#98]
[ 19%] Built target nmos_is05_schemas_static
[ 20%] Built target json_schema_validator_static
[ 21%] Built target mdns_static
[ 73%] Built target nmos_is04_schemas_static
[ 75%] Built target nmos_is09_schemas_static
Scanning dependencies of target nmos-cpp_static
[ 75%] Building CXX object CMakeFiles/nmos-cpp_static.dir/nmos/client_utils.cpp.o
[ 75%] Building CXX object CMakeFiles/nmos-cpp_static.dir/nmos/connection_activation.cpp.o
[ 76%] Building CXX object CMakeFiles/nmos-cpp_static.dir/nmos/connection_events_activation.cpp.o
[ 76%] Building CXX object CMakeFiles/nmos-cpp_static.dir/nmos/connection_api.cpp.o
/home/nmos/nmos-cpp/Development/nmos/client_utils.cpp: In function ‘web::websockets::client::websocket_client_config nmos::make_websocket_client_config(const settings&)’:
/home/nmos/nmos-cpp/Development/nmos/client_utils.cpp:75:16: error: ‘class web::websockets::client::websocket_client_config’ has no member named ‘set_ssl_context_callback’
         config.set_ssl_context_callback(details::make_client_ssl_context_callback<web::websockets::client::websocket_exception>(settings));
                ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/nmos/nmos-cpp/Development/nmos/client_utils.cpp:7:
/home/nmos/nmos-cpp/Development/cpprest/details/system_error.h: In instantiation of ‘ExceptionType web::details::from_boost_system_system_error(const boost::system::system_error&) [with ExceptionType = web::http::http_exception]’:
/home/nmos/nmos-cpp/Development/nmos/client_utils.cpp:44:86:   required from ‘std::function<void(boost::asio::ssl::context&)> nmos::details::make_client_ssl_context_callback(const settings&) [with ExceptionType = web::http::http_exception; nmos::settings = web::json::value]’
/home/nmos/nmos-cpp/Development/nmos/client_utils.cpp:60:118:   required from here
/home/nmos/nmos-cpp/Development/cpprest/details/system_error.h:71:20: error: no matching function for call to ‘web::http::http_exception::http_exception(std::error_code, const char*)’
             return ExceptionType(to_std_error_code(e.code()), e.what());
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/cpprest/http_client.h:35,
                 from /home/nmos/nmos-cpp/Development/nmos/client_utils.h:4,
                 from /home/nmos/nmos-cpp/Development/nmos/client_utils.cpp:1:
/usr/local/include/cpprest/http_msg.h:246:5: note: candidate: ‘web::http::http_exception::http_exception(int, const std::_V2::error_category&)’
     http_exception(int errorCode, const std::error_category &cat) : m_errorCode(std::error_code(errorCode, cat))
     ^~~~~~~~~~~~~~
/usr/local/include/cpprest/http_msg.h:246:5: note:   no known conversion for argument 1 from ‘std::error_code’ to ‘int’
/usr/local/include/cpprest/http_msg.h:223:5: note: candidate: ‘web::http::http_exception::http_exception(int, const string_t&)’
     http_exception(int errorCode, const utility::string_t &whatArg)
     ^~~~~~~~~~~~~~
/usr/local/include/cpprest/http_msg.h:223:5: note:   no known conversion for argument 1 from ‘std::error_code’ to ‘int’
/usr/local/include/cpprest/http_msg.h:212:5: note: candidate: ‘web::http::http_exception::http_exception(int)’
     http_exception(int errorCode)
     ^~~~~~~~~~~~~~
/usr/local/include/cpprest/http_msg.h:212:5: note:   candidate expects 1 argument, 2 provided
/usr/local/include/cpprest/http_msg.h:196:5: note: candidate: ‘web::http::http_exception::http_exception(const string_t&)’
     http_exception(const utility::string_t &whatArg)
     ^~~~~~~~~~~~~~
/usr/local/include/cpprest/http_msg.h:196:5: note:   candidate expects 1 argument, 2 provided
/usr/local/include/cpprest/http_msg.h:188:7: note: candidate: ‘web::http::http_exception::http_exception(const web::http::http_exception&)’
 class http_exception : public std::exception
       ^~~~~~~~~~~~~~
/usr/local/include/cpprest/http_msg.h:188:7: note:   candidate expects 1 argument, 2 provided
/usr/local/include/cpprest/http_msg.h:188:7: note: candidate: ‘web::http::http_exception::http_exception(web::http::http_exception&&)’
/usr/local/include/cpprest/http_msg.h:188:7: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/nmos-cpp_static.dir/build.make:219: CMakeFiles/nmos-cpp_static.dir/nmos/client_utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:272: CMakeFiles/nmos-cpp_static.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by dcrearer** [comment]
So I'm trying to compile the source and the above error is blocking me and I'm not sure how to resolve.

**Comment by dcrearer** [comment]
I was using the wrong version of the cpprestsdk

cpprestsdk/archive/v2.10.8.tar.gz

**Comment by garethsb-sony** [comment]
Yes, sorry, some of the bug fixes in recent cpprestsdk patch versions are quite important so we've ended up also relying on a few of the small recent interface changes.
